# To-do list

## Incomplete exercises

- ~~zSgXP2 (Question is incomplete)~~ 

- ~~MWLCS (Question 3 answer should be -1)~~ Removed the R warning for figure C 

- ~~VcUetN (Need to complete)~~ Removed exercise. Will implement as drill. 

- ~~kUmsBG (Need to complete)~~ Removed exercise. Will implment as drill. 

- ~~EKCIE~~ Re-organized a bit and oriented it toward an essay. 

- ~~BLECL~~ Added the multiple choice question 

- ~~EKCIE (Needs rework)~~ Duplicate of a previous entry

- ~~RDWKW (Move from Chapter 9 to Chapter 8)~~  With the correct chapter numbering, this was moved from Chapter 10 to 9. Also, removed the "reflection" which restated notation concepts previously covered in the textbook.

- ~~YQCLE (References to MMAC must be removed)~~ 

- ~~LDKKVA (The intro to this question should be a part of the actual text of Chapter 10. Question A should be implemented in the standard way, as well.)~~

- ~~UVGMA (Remove; save for Block 4 - Applications)~~ 

- ~~FISHU (Move from Chapter 7 to Chapter 11, also error in the code)~~  

- ~~AVNOW (Move from Chapter 7 to Chapter 11)~~ 

- ~~JWUVA (Remove references to “Hump”)~~

- ~~“Question tmp-8” (should be implemented in the standard way)~~

- ~~“Question tmp-9” (should be implemented in the standard way, and explain what ‘envelope’ means)~~

~~MWDKVA (Remove reference to “hump”)~~

- ~~EDKYV~~ (Remove – I’m not sure what this question is getting at) I kept it in but clarified the introduction.)

- ~~TWLC (Remove and reserve for Block 4 – Applications)~~

- ~~dB1r5F Move from Chapter 6 to Chapter 11~~ 

- ~~drawing (Move from Chapter 6 to Chapter 11)~~

- ~~daylength (Move from Chapter 6 to Chapter 11)~~

- ~~ILESX (part D doesn’t make sense in this context. Move Part D to chapter 15)~~ 

- ~~TLCIX (move to earlier in the chapter)~~


- ~~j3xe (move from Chapter 7 to Chapter 14)~~ 

- ~~ILXEG (Incomplete & Use of the term “decade” is confusing [not covered in text])~~ 

- EWLCI (Use of the term decade is confusing [not covered in text]) 

- TLEXE (Move entire section to be earlier in the chapter) -- I haven't done this. 

- ~~SELIX ( “::: {scaffolding}” showing above one of the code blocks) ~~

- ~~RDTTKW (This is the Satellite project form last year. Too long)~~

 
