# Integration


Sometimes it's easier to think through matters when they are presented in a concrete, everyday context. Imagine that you managing a small-town water tank. Water flows in from the supply system and flows out to consumer demand. At any instant of time, there's a net amount flowing to the tank, which could be measured in cubic-meters-per-second. (If the amount is negative, consumers are momentarily consuming more than is being newly supplied.) 

The amount of water in the tank, measured in cubic meters, also fluctuates over time. We're going to call the water in the tank your "stock" of water. As a water manager, you want to make sure that your stock never goes to zero. (Otherwise, the town's citizens will be without water!)

In terms of functions, the "flow" is $f(t)$. The definite integral of the flow $$\int_a^b f(t) dt$$ gives you some information about the stock: how much the amount of stock has changed from time $a$ to time $b$. This is not, however, exactly the same as the stock. Presumably, there was already some water in the tank at time $a$, so the stock at time $b$ will be that amount plus the amount of the definite integral of $f(t)$.

In this exercise, you are going to use the "Graph-antiD" web app which enables you to visualize the anti-derivative function in terms of areas. To use the app, click-drag-and-release to mark part of the domain of the function being displayed. 


`r insert_calcZ_exercise("XX.XX", "CCwWGB", "Exercises/Accum/tiger-tug-shoe.Rmd")`


`r insert_calcZ_exercise("XX.XX", "rk5PPK", "Exercises/Accum/seahorse-choose-canoe.Rmd")`


`r insert_calcZ_exercise("XX.XX", "DkoUjX", "Exercises/Accum/calf-know-painting.Rmd")`



## Fundamental theorem of calculus



`r insert_calcZ_exercise("XX.XX", "LCKEs","Exercises/Accum/three-perspectives.Rmd")`

`r insert_calcZ_exercise("XX.XX", "KLJRK","Exercises/Accum/falling-from-pisa.Rmd")`

`r insert_calcZ_exercise("XX.XX", "gDSeX","Exercises/Accum/first-fundamental-theorem.Rmd")`
