# Outline of Block 3 {.unnumbered}

::: {.todo}
This section is for development purposes only. It is not to be included in the released text.
:::

This outline was that established during the May 17-19, 2021 working sessions at USAFi. It's copied directly from the Teams document. I've made some modifications which are noted in [[square brackets]] for deletions and **bold face** for additions..

**Adding preliminary intro chapter, motivating a situation where you know the derivative but don't know the function**

1. **Change relationships**

1. Iteration and Euler’s Method
    a. NTI
        i. We’re only going to go by-hand up to 3 iterations of Euler’s method
        i. We’ll show the students a loop, but not make them create the loop
    b. Topics
        i. Tie in loops as (iteration)
        i. Reversing the difference quotient (the slope function $\diff{x}f(x)$)
        i. Initial values
        i. By hand
        i. Implement on a computer
    c. Readings: Chapter \@ref(change-accumulation).
    d. EXERCISES to ADD
        i. Exercises/Accum/chain-of-differentiation.Rmd

2. **Iteration and accumulation**
    b. Topics
        i. Euler's method
        ii. Computing examples of iteration and loops
    c. Exercises
        - Accum/accumulate-numeric-draft.Rmd
        - Accum/computing-and-antiD.Rmd
    d. Readings: Chapter \@ref(iteration-and-accumulation)

2. Accumulation as net change
    a. NTI:
        i. Introduce definition of definite integral as the mathematical notation for accumulation [[(Euler’s method) moved to new Iteration and accumulation]]
    b. Topics
        i. Notation for definite integrals (connected to Euler's method)
            - Exercises/Accum/three-perspectives.Rmd
        iii. **Eyeballing accumulation** This is where area under the curve goes
            a. motivating graph in www/covid-history.png from Economist June 26, 2021 p. 8
            b. [Exercises/Accum/accumulation-limits.Rmd]
            c. [Exercises/Accum/ups-and-downs.Rmd]
            d. [App and exercises: Exercises/Accum/Graph-anti.Rmd]
        iii. Concrete examples of anti-differentiation
            i. Power to energy [Exercises/Accum/solar-example.Rmd]
            ii. Velocity to position [Exercises/Accum/sailing-over-time.Rmd]
            i. Acceleration-velocity-displacement [Exercises/Accum/falling-from-pisa.Rmd]
            i. **Probability**: dnorm and pnorm, Road-cone-metaphor.Rmd in Exercises/Accum
            i. AreaA
        iv. **Accumulating the accumulation** [Exercises/Accum/Glorias-family.Rmd]
        v. **Fundamentals of integration** (that is, the fundamental theorem) [Exercises/Accum/first-fundamental-theorem.Rmd] [what-is.Rmd] [u-on-the-bottom.Rmd] [MMAC-1.Rmd]
    c. Readings: Chapter \@ref(net-change)
    

3. [[Basic antiderivative rules]] **Anti-derivatives of basic modeling functions**
    a. Topics
        i. Composition of pattern-book function with a linear interior function and the pattern seen from the table of derivatives. [See Exercises/Accum/basic-modeling-functions.Rmd & interior-funs-1.Rmd]
        i. Sometimes you need to multiply or divide by a constant to get the form that you can look up in the table of derivatives. Give a new table.
        iii. The constant of integration [Exercises/Accum/lessons-from-euler.Rmd] [App: Exercises/Accum/find-C.Rmd]
        i. [[Exponential functions]] Moved to introductory block
        i. [[Sine and Cosine]]
        i. [[Logarithms]]
        i. [[Power functions]]
        i. [[Simple combinations of all of the above]] Moved to next block

4. Properties of Accumulation
    a. Topics 
        i. Linear properties
            1. Sum and difference
            1. Multiplication by a constant
        i. Reversing limits of integration
        i. Additive property for an inserted limit of integration
        i. Definite integrals of constant and linear functions geometrically
        i. Units and dimension of definite integral [Exercises/Accum/areas.Rmd] [wind-power.Rmd] [Exercises/Accum/Units_of_antiD.Rmd falcon-tell-mug.Rmd] [heat-engine.Rmd]
    b. Exercies
        - Exercises/Accum/properties-of-anti-derivatives.Rmd

5. Advanced algebraic methods
    a. Topics
        i. Antiderivatives by method of substitution
            i. Reversing the chain rule
        i. Antiderivatives by method of integration by parts
            i. Reversing the product rule
    b. Readings: Chapter \@ref(accum-advanced-algebra)

7. Review of all antiderivative methods
    a. Topics
        i. Tables of integrals [Exercises/Accum/function-order.Rmd]
    b. Readings: Chapter \@ref(antidiff-review)
    
8. **Differential modeling**
    c. Readings: Chapter \@ref(differential-modeling)

## Exercises 

Do heating degree days in utilities in integration.

Similarly with power from wind turbines






Orphaned

i. Average value (?)
i. DD-142Z-02/discrete-inputs.Rmd
i. IODs and drill
i. Latex (e.g. DD-142Z-02/three-perspecitives-2.Rmd)

