# Integrals step-by-step

The setting for anti-differentiation (and it's close cousin, integration) is that we have a function $F(t)$ which we do not yet know, but we do have access to some information about it: its slope as a function of time $f(t) \equiv \partial_t F(t)$ and, perhaps, its value $F(t_0)$ at some definite input value.

Chapter \@ref(totaling-bits) showed some ways to visualize the construction of an $F(t)$ by accumulating short segments of slope. The idea is that we know $f(t)$ which tells us, at any instant, the slope of $F(t)$. So, in drawing a graph of $F(t)$, we put our pen to paper at some input value $t_0$ and then move forward in $t$, setting the instantaneous slope of our curve according to $f(t)$.

In Chapter \@ref(net-change), we dealt with one of the limitations of finding $F(t)$ by anti-differentiation of $f(t)$; the anti-derivative is not unique. This is because to start drawing $F(t)$ we need pick a $t_0$ and an initial value of $F(t_0)$. If we had picked a a different starting point $t_1$ or a different initial value $F(t_1)$, the new curve would be different than the one drawn through $(t_0, F(t_0))$, although it would have the same shape, just shifted up or down according to our choice. We summarize this situation algebraically by writing $$\int f(t) dt = F(t) + C\ ,$$ where $C$ is the ***constant of integration***, that is, the vertical shift of the curve. 

The non-uniqueness of $F(t)$ does not invalidate its usefulness. In particular, the quantity $F(b) - F(a)$, will be the same regardless of which starting point we used to draw $F(t)$. We have two names for $F(b) - F(a)$

1. The ***net change*** in $F()$ from $a$ to $b$.
2. The ***definite integral*** of $f()$ from $a$ to $b$, written $\int_a^b f(t) dt$.

These two things, the net change and the definite integral, are really one and the same, a fact we describe by writing $$\int_a^b f(t) dt = F(b) - F(a)$$.

In this chapter, we'll introduce a simple numerical method for calculating from $f()$ the net change/definite integral. This will be a matter of trivial but tedious arithmetic: adding up lots of little bits of $f(t)$. Later, in Chapter \@ref(accum-symbolic), we'll see how to avoid the tedious arithmetic by use of algebraic, symbolic transformations. This symbolic approach has great advantages, and is the dominant method of anti-differentiation found in college-level science textbooks. However, there are many common $f(t)$ for which the symbolic approach is not possible, whereas the numerical method works for any $f(t)$. Even more important, the numerical technique has a simple natural extension to some commonly encountered accumulation problems that look superficially like they can be solved by anti-differentiation but rarely can be in practice. We'll meet one such problem and solve it numerically, but a broad approach to the topic, called ***dynamics*** or ***differential equations***, will have to wait until Block 6.

## Euler method

The starting point for this method is the definition of the derivative of $F(t)$. Reaching back to Chapter \@ref{fun-slopes}, 

$$\partial_t F(t) \equiv \lim_{h\rightarrow 0} \frac{F(t+h) - F(t)}{h}$$
To translate this into a numerical method for computing $F(t)$, let's write things a little differently.

- First, since the problem setting is that we don't (yet) know $F(t)$, let's refer to things we do know. In particular, we know $f(t) = \partial_t F(t)$.
- Again, recognizing that we don't yet know $F(t)$, let's re-write the expression using something that we do know: $F(t_0)$. Stated more precisely, $F(t_0)$ is something we get to make up to suit our convenience. (A common choice is $F(t_0)=0$.)
- Let's replace the symbol $h$ with the symbol $dt$. Both of them mean "a little bit of" and $dt$ makes explicit that we mean "a little bit of $t$."
- We'll substitute the limit $\lim_{h\rightarrow 0}$ with an understanding that $dt$ will be something "small." How small? We'll deal with that question when we have to tools to answer it.

With these changes, we have $$f(t_0) = \frac{F(t_0+dt) - F(t_0)}{dt}\ .$$
The one quantity in this relationship that we do not yet know is $F(t_0 + dt)$. So re-arrange the equation so that we can calculate the unknown in terms of the known. $$F(t_0 + dt) = F(t_0) + dt\, f(t_0)\ .$$
::: {.example}
Let's consider finding the anti-derivative of $\dnorm()$, that is, $\int_0^t \dnorm(x) dx$. In one sense, you already know the answer, since $\partial_x \pnorm(x) = \dnorm(x)$. In reality, however, we know $\pnorm()$ only because it has been numerically constructed by integrating $\dnorm()$. The $\pnorm()$ function is so important that the numerically constructed answer has been memorized by software

:::



## Area



