# (PART) Block 3: Accumulation and anti-differentiation {.unnumbered}



# Back and forth with functions
    
::: {.chapterintro }

Differentiation and anti-differentiation are the back and forth of a tennis game

:::    
    
    Objectives: 
    
    i. (Int-1a) Understand anti-differentiation as the reverse process of differentiation 
    #. (Int-1b) Utilize the following basic rules of anti-differentiation to find the anti-derivatives of the basic modeling functions (MMAC pgs. 632-633): 
        a. Constant Rule 
        b. Power Rule 
        c. Exponential Rule 
        d. Sinusoidal Rule 
        e. Logarithm Rule (i.e. anti-derivative of )

2. **Finding Anti-derivatives**

    Objectives: 

    i. (Int-2a) Utilize Euler’s Method to approximate anti-derivatives when the value of  is small 
    #. (Int-2b) Utilize your knowledge of derivatives rules to backwards solve for anti-derivatives 
    #. (Int-2c) Understand the notation of an indefinite integral to include 
        a. the integrand symbol 
        b. variable of integration ("with respect to" variable)
        c. the constant of integration 
    #. (Int-2d) Understand the relationship between a (child) function  and its (parent) integral
    #. (Int-2e) Determine the units of an anti-derivative given the base function and the variable of integration  
    #. (Int-2f) Understand that the output of anti-differentiation is a function known as a general solution and more information is necessary to find the particular solution 

3. **The Definite Integral**
    
    Readings: 614-616
    
    Objectives: 
    
    i. (Int-3a) Understand the notation of limits of integration within a definite integral 
    #. (Int-3b) Determine to units of a definite integral (MMAC pg. 614) 
    #. (Int-3c) Use the algebraic properties of definite integrals (MMAC pg. 615-616) to calculate definite integrals 
    #. (Int-3d) Calculate definite integrals graphically 

    Additional Resources: MMAC Section 6.2 

4. **The Fundamental Theorem of Calculus**
    
    Objectives: 
    
    i. (Int-4a) Understand the Fundamental Theorem of Calculus Part 2 as how to evaluate definite integrals 
    #. (Int-4b) Comprehend how the Fundamental Theorem of Calculus Part 2 graphically can calculate the area between curves (MMAC pgs. 644-645) 
    #. (Int-4c) Understand the Fundamental Theorem of Calculus Part 1 as the net accumulation function 
    #. (Int-4d) Understand how a definite integral with a variable limit of integration outputs a function 

    Additional Resources: MMAC Section 6.3 & 6.4 only pgs. 640-645  

5. **Understanding Anti-derivatives**
    
    Objectives: 
    
    i. (Int-5a) Determine dimensions and units utilizing a graph 
    #. (Int-5b) Graph the antiderivative of a function given the graph of the base function and a single point on the anti-derivative 
    #. (Int-5c) Know common scientific application relationships between base functions and anti-derivatives 
        a. Acceleration, Velocity, Position 
        b. Force, Work 
        c. Area, Volume 

6. **Further applications of Anti-derivatives**
    
    Objectives: 
    
    i. (Int-6a) Understand the relationship between the hump function and the sigmoidal function 
    #. (Int-6b) Discuss the scientific application of probability density and cumulative probability 
    #. (Int-6c) Understand the concept of expected value 

7. **Algebraic Integration**
    
    Objectives: 
    
    i. (Int-7a) Find the integral algebraically using the technique u-substitution  
    #. (Int-7b) Find the integral algebraically of select functions using Integration by Parts 

8. **Multivariate Integration**
    
    Objectives: 
    
    i. (Int-8a) Conduct anti-differentiation when multiple variables are in the base function 
    #. (Int-8b) Conduct multiple iterations of anti-differentiation when multiple variables are in the base function in the correct order 
    #. (Int-8c) Understand the dimensions and units when integrating with respect to multiple variables    
