# Anti-differentiation

## Reading the table backwards

::: {.objectives}
```{r echo=FALSE, results="markup"}
state_objective("Int-2b", "Utilize your knowledge of derivatives rules to backwards solve for anti-derivatives.")
state_objective("Int-2f", "Understand that the output of anti-differentiation is a function known as a general solution and more information is necessary to find the particular solution [DTK: This is language I associate with differential equations. How about: Find the constant of integration.]")
state_objective("Int-2c", "Understand the notation of an indefinite integral to include 
    a. the integral symbol
    b. variable of integration (\"with respect to\" variable)
    c. the constant of integration
    ")
state_objective("Int-2d", "Understand the relationship between a (child) function  and its (parent) integral.")
```
:::

## The accumulated quantity

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Int-2e", "Determine the units of an anti-derivative given the base function and the variable of integration.")
```
:::


## Graphical construction

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Int-5a", "Determine dimensions and units utilizing a graph.")
state_objective("Int-5b", "Graph the anti-derivative of a function given the graph of the base function and a single point on the anti-derivative.")
```
:::

## Step by step with Euler

::: {.objectives}
```{r echo=FALSE, results="markup"}
state_objective("Int-2a", "Utilize Euler’s Method to approximate anti-derivatives when the value of is small.")
```
:::




