# (PART) Block 4: Manifestations {.unnumbered}

You are far enough along in your study of calculus that we can step away from teaching you calculus concepts and techniques, and look at some of the many ways that these concepts and techniques are appear in the work and theory of the quantitative disciplines. This is mainly where you will encounter calculus in your further studies. We want to make sure you're in a position to recognize the calculus when it is happening.



### Linear combinations



Bohr model of the atom, destructive interference of the wave function, why there are discrete orbitals.


### Probability

Situation of walking along a beach collecting shells of a rate species. The shells aren't evenly distributed along the beach. Perhaps this is due to the underwater topography or isolated kelp forests being offshore in someplaces and not others. Whatever the reason, the observation is the distribution is uneven and you are somewhat more likely to find a shell in some places rather than others. 

How shall we represent this distribution mathematically. Naturally, we can use a function whose input is location along the coast, perhaps measured in km north of a geographic marker. What should the output of the function be?

Let's start with the (incorrect) idea: that the output is the probability of finding a shell at the given location. With this formulation, your favorite shell-hunting location would be the argmax of the function.

Suppose, for instance, you've got your shell-finding function drawn on a map. You and your friend, who took calculus last year take a day off for a field trip. Parking near your favorite spot, where the shell-finding function has an output of 0.1, you hike in on the trail, crossing the sand until you finally arrive at that narrow margin where the shells have been washed by the last high tide. 

Bad luck! No shell today. You start back to the car but your friend calls after you. "The function is continuous. If the output is 0.1 here, then it's going to be close to 0.1 nearby." Your friend proposes to take a step up the shore---let's call it a step of length $h$---to a new spot. "That spot also has a probability of 0.1. We might not find anything there, but if we keep taking steps we'll have many opportunities to find a shell. I bet if we take 20 steps, we will be sure to find a shell at one of the locations." 

You're experience tells you this reasoning is wrong. "No, no no. The 0.1 isn't just the probability of finding a shell at one exact place, it's the probability of finding a shell in the neighborhood of that place."

Your friend asks, "How big is a neighborhood?" You're not sure. And if you don't know how widely you have to search, it's meaningless to assert that the probability is 0.1. So how can you claim to have a shell-finding function.

The resolution to the problem is that the shell-finding function does not have an output that is a probability.  OUTPUT IS PROBABILITY DENSITY, which might be in probability per km. For instance, the shell-finding function is more or less constant over a small interval, say 10 meters. Over those 10 meters, the density is 0.1/km. If you walk a 10 meter length, you will have covered 0.01 km, so the probability of finding a shell on that short walk is $0.1 \text{km}^{-1} \times 0.01 \text{km} = 0.001$: one in a thousand.

Accumulating probability. The probability is a function of how long you walk along the beach. No point just looking at the argmax; that's just where the pickings are relatively easy. Instead, your most efficient strategy is to cover an interval where, on average, the function is highest.

THEN DO THE CALCULATION OF AVERAGE.

