# (PART) Block 6: Decisions with calculus {.unnumbered}

# Simple Comparisons and reductions (NPV and expected value)

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Close-4a", "Recognize two important real-world contexts in which a vector (or function) output applies: a. A cash-flow stream; and b. A probability distribution for an outcome")
state_objective("Close-4b", "Employ Net Present Value (NPV) and Expected Value to convert vector outputs into a scalar for the purposes of optimization")
state_objective("Close-4c", "Compute the NPV of a cash flow stream")
state_objective("Close-4d", "Determine the expected value based on a discrete/continuous probability distribution function")
state_objective("Close-4e", "Compute the expected value of a cash flow stream discounting to the NPV")
```
:::

# Project 3: Life expectancy

# Optimization problems

Should this be in Block 2 under optimization

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Close-6a", "Develop an objective function from a scenario")
state_objective("Close-6b", "Recognize and determine constraints")
state_objective("Close-6c", "Use calculus techniques to determine argmin and argmax")
state_objective("Close-6d", "Recognize the limitations of precision")
```
:::

# Multiobjective optimization

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Close-7a", "Be able to recognize situations where there is more than one objective to be achieved simultaneously.")
state_objective("Close-7b", "Understand that in a multi-objective environment, a \"best\" solution is not always possible.")
state_objective("Close-7c", "Distinguish between commensurate and incommensurate objectives.")
state_objective("Close-7d", "Understand that in general there is no purely mathematical solution to optimization with multiple incommensurate objectives.")
state_objective("Close-7e", "Be able to distinguish between dominating and non-dominating choices")
```
:::

# Constraints and Constrained functions (Part 1)

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Close-8a", "Graphically understand multivariable optimization problems")
```
:::

# Constraints and Constrained functions (Part 2)

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Close-9a", "Understand local extrema in terms of gradient vectors")
```
:::
