# Outline of Block 2 {.unnumbered}

::: {.todo}
This section is for development purposes only. It is not to be included in the released text.
:::

This outline was that established during the May 17-19, 2021 working sessions at USAFA. It's copied directly from the Teams document. I've made some modifications which are noted in [[square brackets]] for deletions and **bold face** for additions..


1. Revisiting Calculating slope
    a. NTI:
    b. Admin:
        i. Sizeable quiz on interlude
    c. Outcomes:
        i. Calculate a slope given two points
        ii. Given a graph of a function, identify graph of its slope function $s(x)$
        iii. Given a graph of the slope function, identify features of the original function
    d. Readings: Chapter \@ref{difference-and-change}

2. Derivatives
    a. NTI:
        i. Explain that limits are the solution to the problem of having an arbitrary $h$ in the slope function
    b. Topics:
        i. Show that there are different definitions of the slope function $s(x)$ that depend on the $h$ selected
        ii. Describe derivative as the limit where $h \rightarrow 0$
        iii. Derivatives of basic modeling functions
        iv. Linear properties of derivatives
        v. [[Derivative is a number; differentiation is an operator]] **We need to introduce operators earlier.
        v. Functions as arguments in R
        vi. Introduce notation: $f'$, $\frac{df}{dx}$, $\partial_x f(x)$, [[$D_x f]]$
        vii. Introduce NaN and Inf
    c. Outcomes:
        i. Find the derivatives of all basic modeling functions
        i. Know the basic properties of differentiation
        i. Continue working graphing a derivative
    d. Readings: Chapter \@ref(h-and-derivatives)

3. Relationships between functions and their derivatives Part I
    a. NTIs:
        i. Split students into A/B pairs. A has graph of derivative. B can't see that graph, but can talk to A. B should sketch out the original function based on information from A, who can see B's sketch. Then reveal answer.
    b. Topics:
        i. Argmax/Argmin
        i. Max/min
        i. Critical points
    c. Outcomes: 
        i. Determine a function’s critical points graphically and algebraically
        i. Determine whether a critical point is a max or min
    d. Readings: \@ref(optim-and-shape). It doesn't take much to introduce max and min from graphs, argmax and argmin, and critical points. So the reading can be quite small.

4. Relationships between functions and their derivatives Part II
    a. NTI:
        i. Curvature. Up like a cup, down like a frown
        ii. 2nd derivative indicates curvature
    b. Topics:
        i. Second derivatives are the slope of the slope
        i. Concavity is the slope of the slope
    c. Readings: Chapter \@ref(optim-and-shape) This is the same as the previous days reading. Maybe we should add a section of chains of derivatives, especially for polynomials, showing how they eventually go to zero.

5. Relationships between functions and their derivatives Part III
    a. Topics:
        i. Knowing $f'(x_0) = 0$ tells you there is a min/max/saddle at $x_0$
        ii. 2nd derivative to distinguish between the three
        iii. Chain of derivatives
    b. Outcomes:
        i. Be able to find max/min, argmax/argmin of given functions graphically.
        ii. **Construct derivative function and use `findZeros()` to locate the argmax and evaluate the function to get the corresponding max
    c. Readings Chapter \@ref(optim-and-shape) Still the same as the previous two days. 
    


6. Continuity, Differentiability, Smoothness, Splines
    a. Topics:
        i. Spline is a piecewise function
        i. Order of continuity
        i. Determine graphically whether a function is continuous or not
        i. Determine order of continuity of a function
    b. Outcomes
        i. **Be able to determine if first derivative of function is continuous from graph of function**
        ii. **Be able to determine if second derivative of function is continuous from graph of function (or by taking the 1st derivative and plotting that)**
        iii. **Be able to demonstrate discontinuities in 3rd derivative of spline**
    c. Readings

7. Differentiation of Products of Functions
    a. Outcomes
        i. Identify when it is necessary to differentiate with product rule
        i. Find the derivative using product rule
    b. Readings

8. Differentiation of Composite Functions
    a. Topics
        i. Identifying a composite function
        i. Chain rule
    b. Homework: Save quotient rule for HW
    c. Outcomes: 
        i. Identify when it is necessary to differentiate with chain rule
        i. Find the derivative using chain rule
    d. Readings
    
9. **Partial derivatives**

9. Local Polynomial Approximation
    a. NTI:
        i. Killer application of Taylor polynomials when Brook Taylor figured out that tools of Newton developed
    b. Topics:
        i. List the benefits of approximation and specifically the benefits of quadratic approximation as opposed to linear approximation
        ii. [[Average rate of change]] moved to Block 1 slope function 
        iii. Tangent Lines
        iv. Quadratic equations
        v. Factorials
    c. Readings

10. Approximation at a point
    a. NTI:
        i. R exercise in constructing a Taylor polynomial computationally
    b. Outcomes:
        i. Calculate a Taylor polynomial
        ii. Use Taylor polynomials to simplify mathematical operations (derivatives, limits, etc.)

**Note: We don't touch the gradient here. Provisionally, I'm moving gradients to the Block on linear algebra.**


