# Convexity and curvature

Looking at the graph of a function, our eyes immediately register the slope at any point we focus on. A glance shows whether the slope at that point is positive or negative. Comparing the slopes at two locales is also an automatic visual task: most people have little difficulty saying which slope is steeper. 

One consequence of this visual ability is that it's easy to  recognize whether a line that touches the graph at a point is tangent to the graph. `r mark(2230)`



-----
`r insert_calcZ_exercise("XX.XX", "ykIBCb", "Exercises/Diff/frog-bid-bed.Rmd")`


`r insert_calcZ_exercise("XX.XX", "QnpuMN", "Exercises/Diff/turtle-send-pot.Rmd")`


`r insert_calcZ_exercise("XX.XX", "kq3t86", "Exercises/Diff/reptile-put-kitchen.Rmd")`








`r insert_calcZ_exercise("XX.XX", "BVRjhF", "Exercises/Diff/goat-pay-pot.Rmd")`


-----


On the other hand, finding a numerical value for the slope is not an automatic process. We need to do some arithmetic, computing rise over run. Or, in the language of calculus, we can calculate the slope by evaluating the derivative function. `r mark(2235)`

Other aspects of functions are also readily discerned from a glance at the function graph.

- ***Concavity***: We can tell within each locale whether the function is concave down, concave up, or not concave.
- ***Curvature***: Generalizing the tangent line capability a bit, we can do a pretty good job of eyeballing the tangent circle recognizing whether a circle has much too large or much too small a radius.. 
- ***Smoothness***: We can distinguish smooth functions from non-smooth ones. Or, as you will see, there are some kinds of smoothness that we can discern and others that are not apparent to the eye. 

This chapter is about how to ***quantify*** these properties. It turns out that this is naturally done by calculating derivatives.  `r mark(2240)`

The following exercises are simply meant to test your **visual** acuity in spotting concavity, tangency, and smoothness. Then we'll move on to the calculations involved.


-----

`r insert_calcZ_exercise("XX.XX", "5ddB5r", "Exercises/Diff/seahorse-speak-saucer.Rmd")`


-----



`r insert_calcZ_exercise("XX.XX", "4nsU0z", "Exercises/Diff/panda-drive-shirt.Rmd")`



## Concavity

Change in the slope


## Curvature

Orthogonal to tangent

Tangent circle to function.

Graphics frame.

We're also pretty good at eyeballing the ***radius of curvature***.  This can be calculated from the first and second derivatives. The radius of curvature operator is $${\cal K} f(x) \equiv \frac{\left|\partial_{xx} f(x)\right|}{\left|1 + \left(\strut\partial_x f(x)\right)^2\right|^{3/2}}$$ `r mark(2245)`

`r insert_calcZ_exercise("XX.XX", "v2doBq", "Exercises/Diff/boy-send-book.Rmd")`
