# Dimensions {#dimensions}



## Arithmetic

Recall the rules for arithmetic dimensioned quantities. We restate them briefly with the square-bracket notation for "the dimension of." For instance, "the dimension of $b$" is written $[b]$. We also  write $[1]$ to stand for the dimension  of a  pure number, that is, a quantity without dimension. 

Operation | Result | Only if satisfies | Metaphor
----------|--------|-------------------|---------
Multiplication | $[a \times b] = [a]  \times [b]$ | anything goes  |promiscuous
Division | $[a \div b] = [a] \div  [b]$ | anything goes  |promiscuous
Addition  |$[a + b] = [a]$|  $[a] = [b]$ | monogomous
Subtraction|  $[a - b] = [a]$ | $[a] = [b]$ | monogomous
Trigonometric | $[\sin(a)] = [1]$ |  $[a] = [1]$ | celibate
Exponential | $[e^a] = [1]$ | $[a] = [1]$ (of course, $[e] = [1]$)| celibate
Power-law  | $[b  ^  a] = \underbrace{[b]\times[b]\times ...\times [b]}_{a\ \ \mbox{times}}$  |  $[a]  = [1]$ with $a$ an integer | exponent celibate
Square root | $[\sqrt{b}] = [c]$ | $[b] = [c\times c]$ | idiosyncratic
Cube root | $[\sqrt[3]{b}] = [c]$  | $[b] = [c \times c \times  c]$ | idiosyncratic
Hump   | $[\mbox{hump}(a)] = [1]$ | $[a] =  [1]$ | celibate
Sigmoidal | $[\mbox{sigmoid}(a)] =  [1]$ | $[a] = [1]$ |celibate



```{exercise, name="dim-formulas"}
```
<details>`r knitr::knit_child("Exercises/Dimension/dim-formulas.Rmd")`</details>

```{exercise, name="dim-params"}
```
<details>`r knitr::knit_child("Exercises/Dimension/dim-params.Rmd")`</details>


```{exercise, name="crow-mean-dress"}
```
<details>`r knitr::knit_child("Exercises/Dimension/crow-mean-dress.Rmd")`</details>


## Dimensional analysis

```{exercise, name="satellite-dimensions"}
```
<details>`r knitr::knit_child("Exercises/Dimension/satellite-dimensions.Rmd")`</details>
