# (PART) Block 5: Dynamical systems {.unnumbered}

# States, Dynamics, Trajectory 

    Objectives: 

    i. (Dyn-1a) Understand the difference between state, dynamics, trajectory 
    #. (Dyn-1b) Understand the difference between continuous and discrete time 
    #. (Dyn-1c) Recognize the form of a differential or finite-difference equation 

2. **Discrete Time difference equations in 1 dimension**

    Objectives: 

    i. (Dyn-2a) Understand how discrete time operates and what a step is  
    #. (Dyn-2b) Define a fixed point in discrete time and determine whether the fixed point is stable or unstable 
    #. (Dyn-2c) Understand the relationship between oscillations and stability as we step through discrete time 

3. **Discrete Time difference equations in 2 dimensions**

    Objectives: 

    i. (Dyn-3a) Learn how to construct future states of a dynamical system in two dimensions given the dynamical rule and the two-dimensional initial condition. 
    #. (Dyn-3b) Appreciate that global dynamics can be complicated, potentially with many fixed points, learn how to identify the locations of the fixed points. 
    #. (Dyn-3c) Understand how local dynamics near a fixed point are comparatively simple and can be meaningfully approximated by a matrix. 
    #. (Dyn-3d) Review the mechanics of matrix arithmetic and iterate a dynamical system written in terms of a matrix. 

4. **Wrap-up Discrete Time difference equations**

    Objectives: 

    i. (Dyn-4a) Understand how eigenvalues can describe the properties of difference equations in discrete time 
    #. (Dyn-4b) Understand sequences as steps through discrete time 

5. **Continuous-Time differential equation in 1 dimension**

    Objectives:

    i. (Dyn-5a) Using slope fields, understand that a differential equation has a family of solutions 
    #. (Dyn-5b) Determine a particular solution to a differential equation in one dimension 
    #. (Dyn-5c) Determine end behavior of a differential equation graphically 
    #. (Dyn-5d) Describe a scenario using proportional or inversely proportional growth with a differential equation 

6. **Continuous-Time differential equation in 2 dimensions**

    Objectives: 

    Determine a particular solution to a differential equation in two dimensions 
    #. (Dyn-6a) Describe a scenario using logistics growth with a differential equation 
    #. (Dyn-6b) Understand the three types of dynamics stable, instable, and saddle points and how lambda values can clearly show which one is which 

7. **Catch-up (Review) Day**

    Objectives: 

    i. (Dyn-7a) Understand the benefits of using the exponential function as an educated guess for a solution to a differential equation 
    #. (Dyn-7b) Comprehend how solutions to differential equations can have complex eigenvalues 
    #. (Dyn-7c) Understand how complex eigenvalues are related to oscillations 

8. **Force-balance equation**

    Objectives: 

    i. (Dyn-8a) Damped harmonic oscillator example
    #. (Dyn-8b) Translate eigenvalues into the description of qualitative dynamics
    #. (Dyn-8c) Understand eigenvectors and their connection to flow fields

9. **Nonlinear phase plane and systems of nonlinear differential equations**

    Objectives: 

    i. (Dyn-9a) Interpret phase plane diagrams, flow field diagrams, and time series plots of nonlinear systems of differential equations
    #. (Dyn-9b) Be able to interpret individual terms in a dynamical function that describes specific relationships among real-world objects
    #. (Dyn-9c) Predator-prey model
    #. (Dyn-9d) Attrition model

10. **Complex Eigenvalues**

    Objectives: 

    i. (Dyn-10a) Understand the benefits of using the exponential function as an educated guess for a solution to a differential equation 
    #. (Dyn-10b) Comprehend how solutions to differential equations can have complex eigenvalues 
    #. (Dyn-10c) Understand how complex eigenvalues are related to oscillations 
