# Parameters for functions {#params-intro}

::: {.underconstruction}
JUST NOTES JUST NOTES
:::


The basic modeling functions such as $e^{kx}$,  $\sin(\frac{2 \pi}{P} x)$, $\text{hump}(x, \text{center}, \text{spread})$, $\text{sigmoid}(x, \text{center}, \text{spread})$ did not come in to the world fully clothed with parameters. The clothes are needed to deal with a modeling necessity: inputs to functions used for modeling are quantities with dimension and units.

Underneath the clothing of basic modeling function, you'll find what we will frivolously call the ***naked modeling functions***. These are without parameters: $e^x$, $\sin(x)$, $\text{hump}(x)$, $\text{sigmoid}(x)$. For each of these functions, $x$ must be a ***pure number***, that is, a quantity without physical dimensions.

DEVELOP THIS: $e^x$ and $\sin(x)$, when used for modeling are composed with a proportionality function. $\text{hump}()$ and $\text{sigmoid}()$ are composed with a straight-line function.

The proportionality and straight-line functions handle the conversion from dimensionful quantities with units into the pure numbers.

HOW THE HUMP AND SIGMOID GOT THEIR PARAMETERS: WE'RE ABSTRACTING FROM A COMPLICATED FORMULA, so it's easier to call them out by name.
:::


