# Calculus: Functions and change {#fun-slopes}

For our purposes, the definition of calculus is

> *The use of functions to model and explore continuous change*

We've introduced in a preliminary way the words "function" and "continuous" as they relate to calculus. The agenda of this chapter is to give specific mathematical meanings to the words "model" and "change."

## Naked modeling functions

Here is a list of functions most of which you have probably seen many times in your mathematics studies.

- $x$, $x^2$, $\sqrt{x}$, $1/\sqrt{x}$, and so on. 
- $e^x$ as well as $2^x$ or $10^x$
- $\sin(x)$ and $\cos(x)$
- $\ln(x)$ as well as $\log_{10}(x)$ and $\log_2(x)$

You will see these functions---or something very much like them---throughout this book. As such, it might be appropriate to call them "core" functions. But we will not. Instead, we refer to these as the ***naked modeling functions***.

There's mathematics ... and then there's the real world. The term ***mathematical modeling*** is about constructing representations of situations or phenomena in the real world in terms of mathematical objects. The advantage of being able to construct models is that models are easy to study, explore, take apart, do experiments on, and deduce the implications of.

We use computers to interact with the world, whether that be record-keeping, communications, media displays, and so on. The "things" that computers work with are always mathematical representations of the real world: models. Computers carry out operations on models. For instance, sound is a real-world phenomenon that resides somewhere between the vibrations of air and the psycho-acoustics of the brain. A simple computer representation of sound is constructed using mathematical stuff: a long series of numbers. Suppose we want to *slow down* sound (say, for someone learning a foreign language) or to speed it up (to get through a slow-paced video) or to translate it into text. The technologies for doing these things are almost always implemented by doing arithmetic or more complicated mathematical procedures on the mathematical stuff.

A major theme of this course is how to make such mathematical representations of real-world phenomena and how to work with the representations to extract the results we want. In particular, we will focus on representations in the form of mathematical functions. (There are other mathematical representations, but functions have a special importance and are ubiquitous in scientific work and computing.) 

As you'll see, when we need a new function for some purpose, we practically always build it out of existing functions. For instance, by dressing up the naked modeling functions of the previous chapter with parameters, we generate the "basic modeling functions" that enable us to interact with the world. 

## Change and slope

You have an solid, intuitive sense of what "change" means. In mathematics, and especially the mathematics of functions, change has a very simple meaning that you have already touched on in your previous math education.

The word that encapsulates "change" in high-school math is ***slope***. For instance, you've undoubtedly had to calculate the slope of a straight line in a graph. You learned about "rise" and "run" and how to read them from a graph or from a formula. The slope is the ratio: rise over run. 

Slope is a lovely ***metaphor*** for change, since everyone has a intuitive sense of the slope of a road or of a hillside. You learned to apply this intuition to reading graphs and the slope of a line. We'll exploit the intuitive ability to read a landscape in order to introduce abstract mathematical ideas in a down-to-earth setting. It's a very effective pedagogical strategy.

But not everything that changes has a "slope." For instance, the population of a country can change, as can the number of new cases of an epidemic disease, the temperature of a cup of coffee, or the distance from Earth of a spacecraft. A major part of learning calculus is generalizing and abstracting the mathematical concept of which "slope" is an example and becoming proficient with mathematical procedures for working with change. 

## Continuous change

Most people are comfortable with the ideas of daily changes in temperature or monthly changes in credit-card debt or quarterly changes in the unemployment rate or annual changes in the height of a child. Such things are easy to record in, say, a spreadsheet. For example, as I write, the weather forecast for the next several days (in southeastern Colorado in mid-May) is

Day | High | Low | Description
----|------|-----|------------
Thursday | 73 | 43 | sunny
Friday   | 72 | 48 | windy
Saturday | 66 | 48 | thunderstorms
Sunday   | 68 | 43 | windy
Monday   | 70 | 39 | sunny
Tuesday  | 70 | 43 | sunny
Wednesday| 66 | 45 | partly cloudy

Such data is said to be ***discrete***. The day is listed, but not the time of day. The high temperature is forecast, but not the time of that high. The "description" is also discrete, one of the several words that are used to summarize the quality of the weather, as opposed to the quantity of rain. 

Calculus is about ***continuous change***. For instance, if the weather bureau provide a web interface that let me enter the date and time to the nearest fraction of a second, they would be giving a way to track the change ***continuously***. Many physical processes are intrinsically continuous, for instance the motion (change in position) of a spacecraft or the height of the tide or the stress on a tree as a function of wind velocity.

Finding a language to describe continuous change---famously, the position of the moon or planets in their orbit, or the speed of a ball rolling down a ramp---was central to the emergence of what historians call the "Age of Enlightenment" or "modern scientific method." The first complete presentation of that language was published by Isaac Newton based on his work in the 1660s. As you might guess, the name of the language is "calculus."

## Slopes and curves

::: {.todo}
Review how to compute the slope of a line.

Point out that only the straight-line function has a slope that is the same everywhere. The other naked modeling functions don't have *a slope*, they have a local property that is a function of $x$.
:::



So much of what we will do in calculus depends on being able to construct and manipulate functions. Doing this successfully requires a more careful consideration of how we know when something is a function and the anatomy of functions generally. The major way this is accomplished both in mathematical notation and computer languages is via ***notation***, the subject of the next chapter.

