# Change

Calculus is about change, and change is about relationships. A changing climate is about the relationship between, say, global average temperature and time. It's also about changing levels of CO~2~ and methane, both their production and elimination by atmospheric and geological processes. It's about how burning oil (a change in configuration of the atoms in hydrocarbons) contributes to ocean acidification (the process of change in ocean pH). It's about a whole complex and intricate network of relationships and how change in one component provokes change in others.

This book presents calculus in terms of two simple but central concepts: ***functions*** and ***quantities***. Those words have everyday meanings which are, happily, close to the specific mathematical concepts that we will be using over and over again. Close ... but not identical. So pay careful attention to the brief descriptions that follow.

## Quantity vs number

A mathematical ***quantity*** is an amount of "stuff." The real-world stuff might be mass or time or length. It equally well can be velocity or volume or momentum or corn yield per acre. We live in a world of stuff, some of which is tangible (e.g., corn, mass, force) and some of which is harder to get your hands on and your minds around (acceleration, crop yield, fuel economy). An important use of calculus is helping us conceptualize the abstract kinds of stuff as mathematical compositions of simpler stuff. For example, crop yield incorporates mass with length and time. Later, you'll see us using the more scientific-sounding term ***dimension*** instead of "stuff." In fact, Chapter \@ref(dimensions) is entirely dedicated to the topic of dimensions, but for now it's sufficient for you to understand that numbers alone are not quantities.

Most people are inclined to think "quantity" is the same as "number"; they conflate the two. This is understandable but misguided. By itself a number is meaningless. What meaning does the number 5 have without more context? Quantity, on the other hand, combines a number with the appropriate context to describe some amount of stuff. So, the first thing you need to know about any quantity is the kind of stuff it describes. A "mile" is a kind of stuff: length. A meter is the same kind of stuff: length. A liter is a different kind of stuff: volume. A gallon and an acre-foot are the same kind of stuff: volume.

"Stuff," as we mean it here, is what we measure. As you know, we measure with ***units***. Which units are appropriate depends on the kind of stuff. Meters, miles, microns are all appropriate units of length, even though the actual lengths of these units differ markedly. (A mile is roughly a million microns.) 

Only after you know the dimension and units does the number have meaning. Thus, a *number* is only part of specifying a *quantity*.

Here's the salient difference between number and quantity when it comes to calculus: All sorts of arithmetic and other mathematical operations can be performed to combine numbers: addition, multiplication, square roots, etc. When performing mathematics on quantities, only multiplication and division are universally allowed. For addition and subtraction, square roots, and such, the operation makes sense only if the dimensions are suitable.

The mathematics of units and dimension are the equivalent in the technical world of common sense in our everyday world. For instance (and this may not make sense at this point), if someone tells me they are taking the square root of 10 liters, I know immediately that either they are just mistaken or that they haven't told me essential elements of the situation. It's just as if someone said, "I swam across the tennis court." You know that they either used the wrong verb---walk and run would work---or that it wasn't a tennis court, or that something important was unstated, perhaps, "During the flood, I swam across the tennis court."

## Functions

The other central concept in the book is ***functions*** in their mathematical and computing sense; this is the primary topic for Block 1. A function is something that takes one or more inputs and returns an output. In calculus, we'll deal mainly with functions that take one or more quantities as inputs and return another quantity as output. But sometimes we'll work with functions that take functions as input and return a quantity as output. And there will even be functions that take a function as inputs and return a function as an output.

You've almost certainly seen functions expressed in the general form $f(x)$. The function is $f()$, the input is $x$. Perhaps it's obvious at this point that $x$ is a quantity. $f(x)$ is the operation performed on that quantity. In computing, there are definite, widely used, notations to identify the output of a function. Strangely, in high-school mathematics there is not. This is a major source of confusion both to students learning calculus and professionals using computers to do the work of calculus.

It's possible to present calculus without functions. For instance, Isaac Newton, the inventor of calculus, spoke of "flowing quantities."^[In Newton's language, a "flowing quantity" was a *fluent* and the change in a flowing quantity was a *fluxion*.]

It's practically impossible (and generally unwise) to do computing without functions. They are a basic building block of every mainstream modern computer language. Since the operations of calculus in actual practice are performed on the computer, common sense suggests that we should describe calculus in terms of functions. That's what we will do in this book.

For you, this may take a bit of getting used to. The reason is that the notation used in high-school algebra and in almost all calculus texts is not the notation of functions. For example, almost all students have seen a mathematical ***expression*** in this form: $$y = m x + b$$
Using the language of math classes, we can say that the expression "describes a relationship between two variables." And from your experience, you know that the ***variables*** are $x$ and $y$. The other letters, $m$ and $b$, are something else. Many students will reflexively call them the "slope" and "intercept" of the "line." 

You are so used to this that you probably don't see the huge ambiguity involved. For instance, what is a variable? Common sense suggest that it's a thing that varies. But if we know the value of $x$, is it still a variable? In statistics, a variable is something else entirely: a trait. Since statistics and mathematics are used together, this is bound to bring confusion.

Or consider famous famous sentence in high-school mathematics:
$$y = m x + b$$


The notation of equations is a poor substitute for the notation of functions. For instance, what is the input and what is the output? It's not explicitly stated. If, using the allowed manipulations of algebra, we re-arrange $$y = m x + b \ \ \text{into}\ \ \ m = \frac{y-b}{x}$$  do we still have a function? If so, is it the same function as $m x + b$? Would $x$ be the input or would both $x$ and $y$ be inputs? How about $b$? And in the re-arrangement, we have a problem if $x$ is zero, a problem we would never encounter in the original $y=mx+b$.

The engineers and mathematicians who invented computer languages realized  that they had to be explicit in identifying the input, the output, and the function itself; computers demand unambiguous instructions.^[Actually, it's common to give computers ambiguous instructions. The computer will carry out the instruction in the way it does, which may not be anything like what the programmer expected or intended.] Sorting this out was a difficult process even for those mathematically talented and skilled pioneers of notation. So, you can be forgiven for the occasional confusion you have when dealing with notation that pre-dates computing. 

In this book we'll be explicit and consistent in the ways we denote functions so that you can always figure out what are the inputs and how they are being translated into the output. A good start in learning to read the function notation is to see the equivalent of $y=m x + b$ in that notation: $$g(x) \equiv m x + b$$ 
Notice that we're using $\equiv$ (with three parallel bars) rather than $=$. And there's no $y$. The $x$ appears in parentheses on the left side of $\equiv$ to say explicitly "$x$ stands for the input." The notation provides a place to state the ***name*** of the function, in this case $g()$, so that we can refer to the function unambiguously when we are doing operations on it. Since often we'll be using many functions at the same time, it's helpful to have a way to distinguish them by name. The functional notation makes it easy to create many different names: not just $y$ but  $g_\star()$, $h_\text{altitude}()$, azimuth(), and so on. Try that with $y$

## The naked modeling functions {#naked-intro}

Experience allows us to make a short list of mathematical functions that provide a large majority of the tools for representing the real world as a mathematical object. Think of this list as different actors, each of whom is skilled in portraying an archetypical character: hero, outlaw, lover, fool, comic. A play brings together different characters, costumes them, builds on dialog. 

A mathematical modeler is a kind of playwright. She combines mathematical character types to tell a story about relationships. But there is only a handful of archetypical mathematical functions, the analog of the character actors in drama and comedy. We are calling these the ***naked modeling functions***. In writing a mathematical model, you will clothe the actors to suit the era and location and assemble them together in harmony or discord. 

Here is a list of our basic, unadorned functions, the naked model function, 

* Exponential $e^x$
* Logarithm $\ln(x)$
* Power-law $x^p$
* Sinusoid $\sin(x)$
* Straight-line $m x + b$
* Hump $\text{dnorm}(x)$
* Sigmoid $\text{pnorm}(x)$

We've written these here in a traditional notation so that you can see the connections to the math you've already studied. We've used $x$ to stand for the single input to these functions just because that's traditional. 

It's good to refer to the functions by their word name---exponential, logarithm, power-law, sinusoid, straight-line, etc. This helps to avoid the source of common confusion. For example, the mathematical expressions $e^x$ and $x^e$ are easily confused, but they are notation for ***utterly different patterns***. You won't so easily mistake "exponential" and "power-law." 

::: {.takenote}
One important point to make here is that our list of naked modeling functions is very short. You should memorize the names and be able easily to associate each name with the traditional notation. 

Over the next several chapters, we will introduce several features of functions. Some of our basic modeling functions have these features, some don't. These features include:

- monotonicity up or down
- concavity up or down
- horizontal asymptotes
- vertical asymptotes
- periodicity

By the end of Block 1, you should be able to list all seven basic modeling functions and say which of these features are relevant to each.

:::

You will also use and see the computer names for these functions. The names can differ somewhat from one computer language to another, but the names in the language we will use, R, are easily recognized by programmers who use any other language.

For ease of reference, here's a table

Name | Traditional notation | R expression
-----|----------------------|---------------
Exponential | $e^x$ | `exp(x)`
Logarithm | $\ln(x)$ | `log(x)`
Power law | $x^p$ | `x^p`
Sinusoid | $\sin(x)$ | `sin(x)`
Straight-line | $m x + b$ | `m*x+b`
Hump |   | `dnorm(x)`
Sigmoid | | `pnorm(x)`

We've left out the traditional notation for the hump and sigmoid because there isn't a standard one. Surprisingly, there is no specific name in R for the Power law or Straight-Line functions, but it's easy to implement them when needed using the code above.

You noticed that the section heading is "The naked modeling functions." We mean "naked" in a metaphorical sense, and chose the metaphor to make it easy to remember. Think of this list of seven functions as the celebrities of the world of calculus. Unlike human celebrities who appear and wane over the years, and marry and divorce each other frequently, these celebrities have been with us for generations and maintain intimate connections with one another that reflect the nature of mathematics rather than the fads and fancies of celebrities. (Mastering calculus is largely a matter of becoming familiar with the mathematical connections. You'll see these in due time.)

These (basic) celebrity functions appear in many mathematical settings, just as a human celebrity strives to maintain a public image. The human celebrity is a human organism and that organism is naturally naked. In public appearance, however, the celebrity always is clothed in one way or another. (OK ... Rarely some of them appear unclothed and the same is true in mathematics.) In other words, in order to interact with the world at large, the celebrities need attire. 

Similarly, the mathematical functions that appear in real-world applications---as opposed to most math textbooks---always wear clothes, they are adorned with what we call ***parameters***. Parameters help them deal with the units and dimension of quantities. And just as there are standard elements of clothing: shirt, skirt, trousers, ... there are standard ways of clothing the naked modeling function. The process of decorating basic modeling functions is called the ***parameterization*** of the function, and there are often multiple ways of paremeterizing the same function.

Once we dress the naked functions---that is, *parameterize* them---they will become the superheroes of calculus. We'll call this league of superheroes the ***basic modeling functions***..

::: {.forinstructor}
To be consistent, $mx + b$ is not really naked. The naked equivalent is simply $x$. Almost always, the way we will clothe functions is to replace the naked $x$ with $mx + b$
:::


