# Outline of Block 1 {.unnumbered}

::: {.todo}
This section is for development purposes only. It is not to be included in the released text.
:::

This outline was that established during the May 17-19, 2021 working sessions at USAFA. It's copied directly from the Teams document. I've made some modifications which are noted in [[square brackets]] for deletions and **bold face** for additions..

Block 1 Functions and Mathematical Modeling

1. Intro to the course
    a. NTI
        i. We can make the point about Linear Function is the model for change by drawing pictures or discussing how certain quantities change between two points in time
        i. The discussion about Calc Z should not be about "How is Z different", but "Z is the new Calculus to which USAFA is transitioning; you may see differences between this course and the traditional course that some of your peers are taking."
        i. Oveall goal for day 1 is to build cadet's confidence that they can be successful. This requires us to show them the systems, resources, philosophy, and expectations (e.g., college $\neq$ high school) behind the course.
    a. Lecture Topics
        i. Calculus Z overview and trajectory
        i. Course resources and systems
        i. Calculus is the study of change
        i. Linear Function is the model for “change” because it has "slope"
    a. Outcomes
        i. Understand than an equation relates quantities, but a function maps inputs to outputs
        i. Understand the difference between $\equiv$ and $=$
        i. Be able to identify a function's input
    a. Readings (assigned M1, skim before, read after)
        i. Chapter \@ref(change)
    a. Additional Resources
        i. None
    a. Assignments
        i. HW01
        i. Feedback01
        i. DD01

2. Basics of modeling functions
    a. NTI
        i. Emphasize that functions map inputs to outputs, but the pattern-book functions are (by themselves) not flexible enough for most circumstances
        i. Show students graph of 5 pattern-book functions, have them pick which is which. (Use e.g. `slice_plot(sin(x) ~ x), domain(x=c(-5,5)))`)
        i. Show scatter plot of $f(x)\equiv -x+2$ and explain why $f(x)\equiv x$ is not a good model to motivate basic modeling function. [[[Do we want to make up data for this scatter plot? If so, `Mydata <- tibble(x = rnorm(100), y = -2*x + rnorm(100)/10)`]]] See [book position 295](https://dtkaplan.github.io/CalcZ-notes/pattern-book.html#295) for some actual data.
    a. Lecture Topics
        i. Pattern-book functions
        ii. **Basic shapes and features** such as zero crossings, maxima, slope, curvature, horizontal/vertical asymptote (if any). (It's the vocabulary that we want them to know at this point.)
        i. [[Basic Modeling functions and their behaviors based on their parameters]]-save this for another day.
    a. Outcomes
        i. Know graphs, domains, ranges, horizonal/vertical intercepts & asymptotes (if any) for all the pattern-book functions
        i. Recognize that functions are a way of modeling relationships in the real-world
        i. [Given parameters, describe how those parameters affect the shape of the function]]-save this for another day
    a. Readings:  Chapter \@ref(pattern-book)
    a. Additional Resources
        i. [PDF - Exponential Functions Deep Dive](https://usafa0.sharepoint.com/:b:/s/Math142ZFall2021-CalculusI/EfEx-HgBYHNDn2BS4Kadmx0Bytv7CScY0VVyFbngc2GLUw?e=9nDd3s)
        i. [Math Insight - Logarithm basics](https://mathinsight.org/logarithm_basics)
        i. [Khan Academy - Properties of Logarithms](https://www.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:logs#x2ec2f6f830c9fb89:log-prop)
        i. **RESOURCE FOR TRIG VALUES (TRIG TABLE)**
    a. Assignments
        i. Problems at end of chapter (to be written)
    a. Quiz question: Which of these functions have horizontal asymptotes? [Give a list, ask them to circle.] Similar for vertical asymptote.

3. Functions as I/O and Notational Structure of functions (R<>Math)
    a. NTI
        i. Rewrite $y=mx+b$ as $mx-y+b=0$ to show function notation eliminates ambiguity of IO
        i. Break student habit of using "x-axis" or "y-axis"; describe these as "horizontal" or "vertical" axes
        i. Break student habit of using "x" and "y"; instead they should say "input" and "output"
        i. Explain that parameters scale or shift inputs/outputs. Ex: the $C$ in $Ce^{kt}$ scales the output and the $k$ scales the input
        i. Example function without a formula: $f:Cadet\to RoomNumber$
    a. Topics
        i. Functions as Input and Ouptut (IO)
        i. Introduce Multi-input functions
        i. Function Representations
        i. Notation and Conventions
        i. Distinguish between mathematical symbols: $=$, $\equiv$, \rightarrow$, `<-` See Secton \@ref(foursigns)
    a. Outcomes
        i. Understand that a function maps inputs to outputs
        i. Given an input, be able to find the output of a function in any one of the five standard forms:
            - Graphs of functions (including contour plots)
            - Tables of inputs and outputs
            - Word descriptions
            - Computer function name
            - Mathematical notation
        i. Be able to translate between traditional math notation and R expressions
    a. Reading: Chapter \@ref(fun-notation) & \@ref(graphs-and-graphics)
    a. To do:
        - Provide glossary of notation across 6-blocks (+alternate forms)
    a. Assignments
        i. DD03
        
QUIZ: Draw reasonable sketches of all nine pattern-book functions. In addition to the overall shape of the function, label one point  on the graph with its exact output value. (Hint: for $\dnorm(x)$, the highest possible output is 0.3989423.)
    
4. Parameterized functions as models
    a. NTI
        i. Introduce idea that input has meaning, and output has meaning relative to the input
        i. Give students a function. Then change the units of input to a different unit (e.g. feet go to Meters)
        i. Logarithms are not necessarily used as the end model; they are the lever which separate power from exponential functions
            - TODO: Think about physical phenomenon that would appropriately be modeled by a Logarithmic function or power with $p<1$
        i. Focus the lesson entirely on finding parameters for Sine, Power, and Exponential
    a. Lecture Topics:
        i. Modeling phenomenon with the basic modeling functions
        i. How to find parameters for basic modeling functions
            - Linear
            - Sine
            - Power
            - Exponential
            - Logarithmic (note)
    a. Objectives
        i. Given a description of a real-world scenario, be able to identify the appropriate basic modeling function
        i. Given data, select parameters of the basic modeling functions that "fit" the data
    a. Reading: Chapter \@ref(params-intro)
    a. Quiz questions: Draw from MWLCS

5. [[Combining 2+ functions]] I've integrated this with the "Parameterized function" chapter.
    a. Examples
    a. NTIs
    a. Topics
        i. Linear Combination (ex: Polynomial)
        ii. Composition with scaling function ($e^{kt})
            1. Gallons/$ to Liters/Euros
        iii. Composition (affine shift)
            1. Fahrenheit <> Celsius

5. **The modeling process**
    a. NTI:
        i. Examples of mechanistic model situations:
            a. Heat engine: Work extracted from heat when going through a complete cycle. 
                i. Need to know that pressure times volume is work.
                ii. Need to know how a heat engine works: compression (work in), heating, expansion (work out), cooling
                iii. Area of loop is work
            b. Law of mass action: speed of reaction as a function of the concentration of the components. Should it be the product, the sum, ... what?
        ii. Examples of data modeling
            a. Effectiveness of vaccines. 
                i. Measure age, health, level of exposure, vaccination status, whether and when fell ill with COVID.
                ii. Model probability versus time as a function of age, health, exposure, vaccination. That function can then be compared for vaccination and non-vaccination status. If p(t | vaccinated) < 0.1 p(t | not vaccinated), holding other variables constant, then vaccine is more than 90% effective.
    b. Topics
        i. Exponentials 
            a. function asymptotically approach baseline, but since it takes an infinite time to get there, we start by making an educated guess.             b. If there's relevant theory, use that. 
                i. E.g. objects cool to ambient temperature is a nice theory. But even that isn't complete: radiative balance with environment, latent heat of evaporation, ...
                ii. Things with a zero baseline: loss of velocity with friction or air resistence over time; value of invested money; discounted value of future money.
            b. Once you make a baseline guess, check it. For instance, for exponential decay ...
                i. Figure out how long it takes to go from distance $h$ from baseline to distance $h/2$. Then measure how long it takes to go from distance $2h$ to $h$. If the baseline is correct, those two durations should be the same. If the $h \longrightarrow h/2$ duration is shorter than $2h\longrightarrow h$ duration, then baseline was too high. Work through an example and iterate in on reasonable answer.
                ii. Given baseline, finding doubling or halving time and convert this into the value of $k$ in $e^{kt}$.
        ii. Sinusoids. 
            a. Easy to see parameters: baseline, amplitude for sinusoid, first positive-going baseline crossing. 
            b. Hard to see parameter: period. Best to measure duration to go through several cycles, then divide by number of cycles to get period.
        iii. Hump/gaussian function.
            a. Center is pretty easy: argmax
            b. Emphasize rules of thumb for spotting the width: 
                i. half-width at 60% height.
                ii. distance from center marking transition from concave down to concave up.
            c. This width has a strange name: "standard deviation"
            d. [German 10 mark note commemorates Gauss and gaussian](https://www.worldbanknotescoins.com/2013/05/10-deutsche-mark-banknote-carl-friedrich-gauss.html)
        iv. Sigmoid
           a. Center is argument that gives rise to 1/2 of asymptotic value.
           b. Width is distance from center to point where function value is 84% of full range or 16% of full range.
    c. Readings: Chapter \@ref(process-of-modeling)

6. Slope function
    a. NTI:
        i. How do broaden the idea of describing the slope of a line to a general function?
        ii. No $h$ at this point
        iii. The slope function is a function $s()$  which is built from a function $f()$
    b. Topics
        i. Average rate of change.  (Example: Quarterly return of stocks. HW of tree harvesting.) (Example 2: Sine wave with difference around 1 period. Or maybe this becomes low-pass filter example in accumulation.)
        i. $s(x) \equiv \frac{f(x + 0.1) - f(x)}{0.1}$
        ii. Except for linear function, slope **function** depends on how big $h$ is. So let's fix $h$ while we figure things out.
        ii. **Every function has a slope function.**
        iii. **It's helpful to name functions so we know where they come from. We're going to use $f'()$ to stand for the slope function of $f()$**
    c. Reading: Chapter \@ref(fun-slopes)

7. Composition Generally
    a. NTI:
        i. What temperature is it while driving up a mountain?
        ii. Problem where they are calculating the slope of a sigmoid
    b. Topics:
        i. Formula for Gaussian (exponential with a quadratic)
        ii. **Driving up a mountain** temperature vs altitude, altitude vs road position, road position vs time
        iii. Gaussian is the slope function of Sigmoid 
    c. Reading: Chapter \@ref(fun-assembling)

8. Multiplication of functions
    a. NTIs:
        i. Multiplication about Sines, exponential, gaussian, sigmoid
    b. Topics:
        i. Multiplying functions **of the same inputs** gives a function of those inputs.
        ii. **Multiplying functions of different inputs** gives a function whose inputs are the union of the inputs to the multiplicands.
    c. Be able to reverse engineer these products: sin*exp, sin*hump*, sin*sigmoid
    d. Reading: Chapter \@ref(fun-assembling)

9. Multivariate functions
    a. NTIs:
        i. Ask students how they compute the slope of a multi-input function as best they can imagine how (homework?) Build their imagined function (for the slope) and plot the function
    b. Outcomes:
        i. Be able to read & construct (in R) Contour Plots
        ii. Be able to read & construct (in R) Surface Plots
        iii. Be able to read a table w/ 2 inputs
    c. Reading: Chapter \@ref(fun-multiple-inputs)
    
10. Piecewise functions [jettison if needed in favor of doing this as homework]
    a. Topics
        i. Construct and evaluate piecewise functions
        ii. Demonstrate how to implement in R
    b. Outcomes:
        i. Be able to identify break(s) of a piecewise function
        i. Be able to evaluate a piecewise function at a given input
        i. Be able to implement a piecewise function in R
    c. Reading: Chapter \@ref(fun-piecewise)

11. Iterative Modeling
    a. NTI:
    b. Examples:
        i. Tides
        ii. Cooling Water
    c. Objectives:
        i. Describe differences between two models and between a model and data
        ii. Identify disagreements between the model and data
    d: Reading: NEED LINK TO CHAPTER


**Review, GR, Project Days**


12. [[Semi-log Log-log plots]] Magnitude and log
    a. Topics:
        i. Introduce the idea that using logarithms converts a number to its order of magnitude
    b. Outcomes:
    c. Reading: Chapter \@ref(magnitudes)

**Flexible catchup day**


13. Dimensional Analysis 
    a. Reading: Chapter \@ref(dimensions)
    
    1.5 class days

::: {.takenote  data-latex=""}
One of our highlighting formats, called `::: {.takenote  data-latex=""}` is being used as a clear statement of basic skills that a students should master. It might be good to tie quizzes to these and *vice versa*.
:::
