# (PART) Block 4: Linear combinations {.unnumbered}

# Vectors and Vector Operations

    
::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Vec-1a", "Know that vectors can be represented as columns of data or graphically arrows")
state_objective("Vec-1b", "Know how to perform scalar multiplication and vector addition")
state_objective("Vec-1c", "Understand the transpose operator and how to compute the dot product between two vectors")
state_objective("Vec-1d", "Calculate the length of a vector")
state_objective("Vec-1e", "Know that computing the dot product of a vector with itself is equivalent to length squared")
```
:::

# Linear Combinations of Vectors

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Vec-2a", "Write a system of linear equations as an equivalent target problem involving a linear combination of vectors")
state_objective("Vec-2b", "Know the definition of a linear combination of vectors and be able to rewrite as a matrix times a vector")
state_objective("Vec-2c", "Solve for a target vector algebraically or graphically in two dimensions")
state_objective("Vec-2d", "Know how to calculate the distance between two vectors and how to subtract vectors algebraically and graphically")
```
:::

# Orthogonal Vectors and Projection

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Vec-3a", "Calculate the angle between two vectors")
state_objective("Vec-3b", "Find a nonzero vector orthogonal to a given vector")
state_objective("Vec-3c", "Calculate the projection of a vector onto another vector")
state_objective("Vec-3d", "Sketch the projection of one vector onto another and then draw the residual vector")
```
:::

# Solutions of Linear Combination (Day 1)

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Vec-4a", "Write a target problem in the form")
state_objective("Vec-4b", "Understand the relationship between b and b hat and calculate the residual vector")
state_objective("Vec-4c", "Calculate solutions to vector equations using R")
```
:::

# Solutions of Linear Combination (Day 2)

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Vec-5a", "Understand applications of projections")
state_objective("Vec-5b", "Understand the relationship between projections and Method of Least Squares")
state_objective("Vec-5c", "Understand what the qr.solve() function gives you (this is testable).")
```
:::

                                                        
# Method of Least Squares (Day 1)

    ::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Vec-6a", "Apply projections to decompose a vector into two directions")
state_objective("Vec-6b", "Understand the connection between projections into the model space and solutions to the target problem")
state_objective("Vec-6c", "Know that R2 is a measure of how well the model accounts for variability in the output variable")
state_objective("Vec-6d", "Know that R2 is the cosine of the angle between  and")
```
:::

# Method of Least Squares (Day 2)

::: {.objectives}
```{r echo=FALSE, results="asis"}
state_objective("Vec-7a", "Understand that \"continuous\" functions can be approximated by vectors of discrete function value samples")
state_objective("Vec-7b", "Be aware that the word \"transform\" in this class' context relates to the \"Fourier Transform.\"")
state_objective("Vec-7c", "Understand that the \"transform\" technique amounts to designing the matrix in the target problem to break up the function into meaningful components")
```
:::
