
## Chapter 4

`r insert_calcZ_exercise("4.XX", "fiSV7o", "Exercises/GoodQuestions/seal-wake-bed.Rmd")`

## Chapter 5

`r insert_calcZ_exercise("5.XX", "SgdjDO", "Exercises/GoodQuestions/giraffe-build-table.Rmd")`

## Chapter 13

`r insert_calcZ_exercise("13.XX", "sAXvX2", "Exercises/GoodQuestions/monkey-leave-drawer.Rmd")`



## Chapter 18

`r insert_calcZ_exercise("18.XX", "U5TivI", "Exercises/GoodQuestions/goldfish-blow-pencil.Rmd")`

`r insert_calcZ_exercise("18.XX", "EdqXeY", "Exercises/GoodQuestions/fawn-tug-dish.Rmd")`

## Chapter 20

`r insert_calcZ_exercise("20.XX", "JnAuol", "Exercises/Diff/crow-begin-bottle.Rmd")`

## Chapter 21

`r insert_calcZ_exercise("21.XX", "n4bUeW", "Exercises/GoodQuestions/elephant-wake-dress.Rmd")`

`r insert_calcZ_exercise("21.XX", "6PDu06", "Exercises/GoodQuestions/kangaroo-grow-drawer.Rmd")`

## Chapter 22



## Chapter 25

`r insert_calcZ_exercise("25.XX", "8nfvTo", "Exercises/GoodQuestions/crow-swim-chair.Rmd")`

`r insert_calcZ_exercise("25.XX", "WOuYC3", "Exercises/GoodQuestions/aspen-tug-sofa.Rmd")`

