# (PART) Orientation {.unnumbered}

1. Exercises often have feedback for the right or wrong answer.
2. But not always. These are marked with an icon.
3. Sandboxes -- to be opened in another window. We often give "scaffolding" to get you started. Just copy and paste this into the sandbox.

# Themes {.unnumbered}

- functions
- computation
    - notation
    - universality: calculus is not just for the mathematical functions that can be written with a formula. Separates algebraic work from ability to use calculus.
    - iteration
        
        
- formula reading
- units and dimension


# Short response Exercises {.unnumbered}

`r insert_calcZ_exercise("XX.XX", "", exercise_file("01", "exercise-intro.Rmd"))`

# Computing {.unnumbered}

`r insert_calcZ_exercise("XX.XX", "xdews", exercise_file("01", "sandbox-intro.Rmd"))`

`r insert_calcZ_exercise("XX.XX", "kclrh", exercise_file("01", "MMAC-01.Rmd"))`

`r insert_calcZ_exercise("XX.XX", "ekskgggd", exercise_file("01", "MMAC-01.Rmd"))`

`r insert_calcZ_exercise("XX.XX", "kkwcls", exercise_file("01", "MMAC-01-26.Rmd"))`


