---
id: "camel-begin-piano"
created: "Fri Aug 13 10:01:53 2021"
global_id: "jG4rie"
format: "On paper"
---

Consider this function, defined piecewise:

$$h(x) \equiv \left\{
\begin{array}{lcl}0 & & x < 0\\ & \text{for} & \\x^2 &  & 0 \leq x\end{array}\right.$$

1. On your homework paper, write down the R command to create this function. (Hint: Remember `ifelse` from Chapter \@ref(fun-piecewise).)

2. Using a `r sandbox_link()`, plot $h(x)$ over the domain $-1 \leq x \leq 1$, then sketch a copy of the graph on your paper.

3. Create the function $\partial_x h(x)$ by differentiating separately each piece of the piecewise function $h()$. Write down $\partial_x h(x)$ using algebraic notation similar to the definition at the top of this problem.

4. Sketch a graph of $\partial_x h(x)$ over the domain $-1 \leq x \leq 1$. You're welcome to use a sandbox, but you may be able to figure out the shape of the graph yourself.

5. The function you sketched in (4) has a name, given in the text in Section \@ref(continuity). What is that name?

Now you are going to do much the same as in items (3), (4), and (5), but instead of the first derivative $\partial_x h(x)$, create, sketch, and name the second derivative $\partial_{xx} h(x)$.

6. Create and write down $\partial_{xx} h(x)$ in algebraic notation.

7. Sketch $\partial_{xx} h(x)$

8. What's the name for this function given in the text in Section \@ref(continuity)?

9. Classify the smoothness of $h(x)$ using the following table:

Smoothness | Criterion
-----------|-----------
$C^0$      | $\partial_x h(x)$ is discontinuous
$C^1$      | $\partial_x h(x)$ is continuous
$C^2$      | $\partial_{xx} h(x)$ is continuous
$C^3$      | $\partial_{xxx} h(x)$ is continuous
$\vdots$   | and so on.
$C^\infty$ | All orders of derivative of $h(x)$ are continous.

