---
id: "fox-know-dress"
created: "Mon Jul 19 18:26:28 2021"
global_id: "2beqIv"
---



Consider the functions shown in the table, all of which involve a domain split at $x=0$ and the pasting together of two individually $C^\infty$ functions:


```{r cn1-1, echo=FALSE, results="markup"}
askMC(r"(Consider $$f_A(x) \equiv \left\{\begin{array}{ccl}x^2 & \text{for} & 0 \leq x\\x& \text{for}& x \leq 0\end{array} \right.$$ How smooth is it?)",
               "discontinuous",
               "+$C^0$+", 
               "$C^1$",
               "$C^2$",
               "$C^3$", 
               "$C^\\infty$",
               random_answer_order=FALSE
)
```

```{r cn1-2, echo=FALSE, results="markup"}
askMC("Consider $$f_B(x) \\equiv \\left\\{\\begin{array}{ccl}x^3 & \\text{for} & 0 \\leq x\\\\0&\\text{for}& x \\leq 0\\end{array} \\right.$$ How smooth is it?",
               "discontinuous",
               "$C^0$", 
               "$C^1$",
               "+$C^2$+",
               "$C^3$", 
               "$C^\\infty$",
               random_answer_order=FALSE
)
```

```{r cn1-3, echo=FALSE, results="markup"}
askMC("Consider $$f_C(x) \\equiv \\left\\{\\begin{array}{ccl}x^3 & \\text{for} & 0 \\leq x\\\\x^3 & \\\text{for}& x \\leq 0\\end{array} \\right.$$ How smooth is it?",
               "discontinuous",
               "$C^0$", 
               "$C^1$",
               "$C^2$",
               "$C^3$", 
               "+$C^\\infty$+",
               random_answer_order=FALSE
)
```

```{r cn1-4, echo=FALSE, results="markup"}
askMC("Consider $$f_D(x) \\equiv \\left\\{\\begin{array}{ccl}x^3 & \\text{for} & 0 \\leq x\\\\x^2&\\text{for}& x \\leq 0\\end{array} \\right.$$ How smooth is it?",
               "discontinuous",
               "$C^0$", 
               "+$C^1$+",
               "$C^2$",
               "$C^3$", 
               "$C^\\infty$",
               random_answer_order=FALSE
)
```

```{r cn1-5, echo=FALSE, results="markup"}
askMC("Consider $$f_E(x) \\equiv \\left\\{\\begin{array}{ccl}x^3 & \\text{for} & 0 \\leq x\\\\-x^2 &\\text{for}& x \\leq 0\\end{array} \\right.$$ How smooth is it?",
               "discontinuous",
               "$C^0$", 
               "+$C^1$+",
               "$C^2$",
               "$C^3$", 
               "$C^\\infty$",
               random_answer_order=FALSE
)
```

```{r cn1-6, echo=FALSE, results="markup"}
askMC("Consider $$f_F(x) \\equiv \\left\\{\\begin{array}{ccl}\\cos(x) & \\text{for} & 0 \\leq x\\\\0 &\\text{for}& x \\leq 0\\end{array} \\right.$$ How smooth is it?",
               "+discontinuous+",
               "$C^0$", 
               "$C^1$",
               "$C^2$",
               "$C^3$", 
               "$C^\\infty$",
               random_answer_order=FALSE
)
```

```{r cn1-7, echo=FALSE, results="markup"}
askMC("Consider $$f_G(x) \\equiv \\left\\{\\begin{array}{ccl}\\sin(x) & \\text{for} & 0 \\leq x\\\\0 &\\text{for}& x \\leq 0\\end{array} \\right.$$ How smooth is it?",
               "discontinuous",
               "+$C^0$+", 
               "$C^1$",
               "$C^2$",
               "$C^3$", 
               "$C^\\infty$",
               random_answer_order=FALSE
)
```

```{r cn1-8, echo=FALSE, results="markup"}
askMC("Consider $$f_H(x) \\equiv \\left\\{\\begin{array}{ccl}\\sin(x) & \\text{for} & 0 \\leq x\\\\x &\\text{for}& x \\leq 0\\end{array} \\right.$$ How smooth is it?",
               "discontinuous",
               "$C^0$", 
               "$C^1$",
               "+$C^2$+",
               "$C^3$", 
               "$C^\\infty$",
               random_answer_order=FALSE
)
```

