---
id: "lamb-rise-sofa"
created: "Tue Jul 20 14:11:00 2021"
global_id: "3ICCCz"
---

For each of the following, say whether the function is a composition $f(g(x))$ or a product $f(x) g(x)$, or neither. Then identify $f()$. For a product, take $f()$ as the function on the left.

- $h_1(x) \equiv \ln(x) e^x$

```{r dedr1, echo=FALSE, results="markup"}
askMC("What is $h_1(x)$?","+product+", "composition", "neither", random_answer_order=FALSE)
```
```{r dedr1b, echo=FALSE, results="markup"}
askMC("In $h_1()$, which of these is $f(x)$?",
      "$\\sin()$", "$\\cos()$", "$\\exp()$", "+$\\ln()$+", "$\\recip()$",
      "$\\pnorm()$", "$\\dnorm()$", random_answer_order=FALSE)
```

- $h_2(x) \equiv \sin(x) \cos(x)$


```{r dedr2, echo=FALSE, results="markup"}
askMC("What is $h_2(x)$?","+product+", "composition", "neither", random_answer_order=FALSE)
```
```{r dedr2b, echo=FALSE, results="markup"}
askMC("In $h_2()$, which of these is $f(x)$?",
      "+$\\sin()$+", "$\\cos()$", "$\\exp()$", "$\\ln()$", "$\\recip()$",
      "$\\pnorm()$", "$\\dnorm()$", random_answer_order=FALSE)
```


- $h_3(x) \equiv \sin(\cos(x))$


```{r dedr3, echo=FALSE, results="markup"}
askMC("What is $h_3(x)$?","product", "+composition+", "neither", random_answer_order=FALSE)
```
```{r dedr3b, echo=FALSE, results="markup"}
askMC("In $h_3()$, which of these is $f(x)$?",
      "+$\\sin()$+", "$\\cos()$", "$\\exp()$", "$\\ln()$", "$\\recip()$",
      "$\\pnorm()$", "$\\dnorm()$", random_answer_order=FALSE)
```


- $h_4(x) \equiv e^{\ln(x)}$


```{r dedr4, echo=FALSE, results="markup"}
askMC("What is $h_4(x)$?","product", "+composition+", "neither", random_answer_order=FALSE)
```
```{r dedr4b, echo=FALSE, results="markup"}
askMC("In $h_4()$, which of these is $f(x)$?",
      "$\\sin()$", "$\\cos()$", "+$\\exp()$+", "$\\ln()$", "$\\recip()$",
      "$\\pnorm()$", "$\\dnorm()$", random_answer_order=FALSE)
```


- $h_5(x) \equiv \sin(x) - \cos(x)$


```{r dedr5, echo=FALSE, results="markup"}
askMC("What is $h_5(x)$?","product", "composition", "+neither+", random_answer_order=FALSE)
```
```{r dedr5b, echo=FALSE, results="markup"}
askMC("In $h_5()$, which of these is $f(x)$?",
      "+$\\sin()$+", "$\\cos()$", "$\\exp()$", "$\\ln()$", "$\\recip()$",
      "$\\pnorm()$", "$\\dnorm()$", random_answer_order=FALSE)
```


- $h_6(x) \equiv e^{x^2}$


```{r dedr6, echo=FALSE, results="markup"}
askMC("What is $h_2(x)$?","product", "+composition+", "neither", random_answer_order=FALSE)
```
```{r dedr6b, echo=FALSE, results="markup"}
askMC("In $h_6()$, which of these is $f(x)$?",
      "$\\sin()$", "$\\cos()$", "+$\\exp()$+", "$\\ln()$", "$\\recip()$",
      "$\\pnorm()$", "$\\dnorm()$", random_answer_order=FALSE)
```


- $h_7(x) \equiv \pnorm(x^2)$


```{r dedr7, echo=FALSE, results="markup"}
askMC("What is $h_7(x)$?","product", "+composition+", "neither", random_answer_order=FALSE)
```
```{r dedr7b, echo=FALSE, results="markup"}
askMC("In $h_7()$, which of these is $f(x)$?",
      "$\\sin()$", "$\\cos()$", "$\\exp()$", "$\\ln()$", "$\\recip()$",
      "+$\\pnorm()$+", "$\\dnorm()$", random_answer_order=FALSE)
```


- $h_8(x) \equiv \pnorm(x) \dnorm(x)$


```{r dedr8, echo=FALSE, results="markup"}
askMC("What is $h_8(x)$?","+product+", "composition", "neither", random_answer_order=FALSE)
```
```{r dedr8b, echo=FALSE, results="markup"}
askMC("In $h_8()$, which of these is $f(x)$?",
      "$\\sin()$", "$\\cos()$", "$\\exp()$", "$\\ln()$", "$\\recip()$",
      "+$\\pnorm()$+", "$\\dnorm()$", random_answer_order=FALSE)
```


- $h_9(x) \equiv 1/\sin(x)$


```{r dedr9, echo=FALSE, results="markup"}
askMC("What is $h_9(x)$?","product", "+composition+", "neither", random_answer_order=FALSE)
```
```{r dedr9b, echo=FALSE, results="markup"}
askMC("In $h_9()$, which of these is $f(x)$?",
      "$\\sin()$", "$\\cos()$", "$\\exp()$", "$\\ln()$", "+$\\recip()$+",
      "$\\pnorm()$", "$\\dnorm()$", random_answer_order=FALSE)
```

