---
id: "rooster-pink"
author: "Daniel Kaplan"
---

```{r include = FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
```

Consider the model presented in class of energy expenditure walking distance $d$ on a grade $g$: $$E(d,g) = (a_0 + a_1 g)d$$ where $d$ is the (horizontal equivalent) of the distance walked and $g$ is the grade of the slope (that is, rise over run). 

We want $E$ to be measured in Joules. 



```{r rooster-pink-QA11, echo=FALSE}
askMC(
  prompt = "What is the dimension of Joules?",
    "dimensionless",
    "$L/T^2$",
    "$T/L^2$",
    "$M/T^2$",
    "$M L/T^2$",
    "$M/L^2$",
    "$M/(L^2 T^2)$",
    "+$M L^2 / T^2$+",
  inline = FALSE,
  random_answer_order = FALSE
)
```

```{r rooster-pink-QA12, echo=FALSE}
askMC(
  prompt = "What is the dimension of the parameter $a_0$?",
    "dimensionless",
    "$L/T^2$",
    "$T/L^2$",
    "$M/T^2$",
    "+$M L/T^2$+",
    "$M/L^2$",
    "$M/(L^2 T^2)$",
    "$M L^2 / T^2$",
  inline = FALSE,
  random_answer_order = FALSE
)
```

```{r rooster-pink-QA13, echo=FALSE}
askMC(
  prompt = "What is the dimension of $g$?",
    "+dimensionless+",
    "$L/T^2$",
    "$T/L^2$",
    "$M/T^2$",
    "$M L/T^2$",
    "$M/L^2$",
    "$M/(L^2 T^2)$",
    "$M L^2 / T^2$",
  inline = FALSE,
  random_answer_order = FALSE
)
```

```{r rooster-pink-QA14, echo=FALSE}
askMC(
  prompt = "What is the dimension of the parameter $a_1$?",
    "dimensionless",
    "$L/T^2$",
    "$T/L^2$",
    "$M/T^2$",
    "+$M L/T^2$+",
    "$M/L^2$",
    "$M/(L^2 T^2)$",
    "$M L^2 / T^2$",
  inline = FALSE,
  random_answer_order = FALSE
)
```
