---
title: "Integral of the day: TEMPLATE"
date: "MMM DD YYYY"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
etude2::load_learnr_safely()
library(gradethis)
library(mosaic)
knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```

```{r context="setup"}
## SET UP THE PROBLEM HERE. 
# Note use of double \\ for latex in quotation marks
problemLatex <- "\\int cos(3 t) dt"
## Remember to set the CHUNK NAMES to match the file name
```

```{r context="server"}
answer_fun <- function(t) sin(3 * t) / 3
evaluate_at <- 1:10
correct_arguments <- c("t")
```


Work out this anti-derivative on paper.

<div style="font-size: 40px; text-align:center;">$`r problemLatex`$ </div>

Once you have your result, translate it into a correct R *function*.

```{r IOD-B, exercise=TRUE, exercise.lines=5, exercise.cap="Integral of the day"}
F <- makeFun()
```

```{r IOD-B-check}
library(magrittr)

gradethis::grade_result(
  fail_if( ~ !is.function(.result), message = "Your result should be in the form of a function."),
  fail_if( ~ !all(c("t") %in% names(formals(.result))),
           message = "It should be a function of t."),
  pass_if( ~ all(.result(1:10) ==
                          sin(3 * (1:10)) / 3)),
  fail_if( ~ TRUE, message="Correct arguments, but not the right function.")
)  
```


Now that you have the correct answer, use Latex to typeset the formula in the function here. Some Latex tips: `a^b` will produce $a^b$, while `\frac{a}{b}` will produce $\frac{a}{b}$.

```{r results="asis"}
etude2::latex_entry_box("latex-B")
```

```{r context="server"}
id <- "latex-B"
answers <- c("\\sin(3 t)/3", "sin(3 t)/3", "1/3 \\sin(3 t)", "\\frac{1}{3} 
             \\sin(3 t)") 
squash_str <- "\\{|\\}| |\t|\n"

# To return the state of the app
if (!exists("app_result")) app_result <- reactiveVal(FALSE) 

output[[NS(id, "rendered")]] <- renderUI({
  withMathJax(paste0("$$", input[[NS(id, "latex")]], "$$"))
})
output[[NS(id, "feedback")]] <- renderUI({
  compare <- gsub(squash_str, "", answers)
  the_answer <- input[[NS(id, "latex")]]
  if (is.null(the_answer)) the_answer <- "missing"
  correct <- gsub(squash_str, "", 
           input[[NS(id, "latex")]]) %in% compare
  if (exists("apps_state")) {
    registration_name <- NS(id, "result")
    apps_state[[registration_name]] <-
      tibble::tibble(id = registration_name, 
                     question = "latex input",
                     answer = the_answer,
                     time = as.character(Sys.time()),
                     correct = correct,
                     attempts = 1,
                     history = "")
    
  }
  ifelse(correct, "✓", "☞")
})
```

