---
title: "FDE vocabulary review"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
```

We are working with two-dimensional discrete-time dynamical systems---"finite-difference equations"---that are centered at a fixed point.

What does it mean that the system is *two-dimensional*?
- two state variables
- the state space is a plane
- 

What does it mean that the system is *discrete-time*?

What does *dynamical system* mean?

What is a *fixed point*?


What does *centered at a fixed point* mean?

What does *finite-difference equation* mean?

Mostly in this course we have been talking about *functions*, mathematical objects that take one or more inputs and produce an output. But most high-school curricula focus on *equations*. Why do we call the dynamical systems finite-difference **equations** rather than finite-difference **functions**?

We keep writing the finite-difference equations using *vectors* and *matrices*? Like this:
$$\left[\begin{array}{c}x_{n+1}\\y_{n+1} \end{array}\right] = 
\left[\begin{array}{cc}a & b \\ 1 & 0\end{array}\right] \cdot
\left[\begin{array}{c}x_n\\y_n \end{array}\right]$$

How are these related to formulas (things like like $3x - 2 y$)?

Where is the fixed point of the [abcd] system?
