---
title: "Multiple objectives"
author: "Daniel Kaplan"
---

```{r include=FALSE, context="setup"}
library(mosaic)
library(mosaicCalc)
library(etude2)
```

It often happens that decisions involve multiple simultaneous objectives. In one context or another, each of these considerations can play a role in decision making:

- safety
- cost
- human life
- animal welfare
- collateral damage
- public or political reaction

This is by no means an exclusive list. 

In specialized domains more specific competing objectives are often part of the design goal. For instance, consider aircraft design: 

- range
- payload or cargo capacity
- short take-off and landing
- maneuverability 
- mission suitability
- multi-mission capability
- maintenability
- stealth

Over the next few lessons, we're going to introduce concepts that are important to effective thinking about designing with multiple objectives as well as mathematical tools that help in balancing conflicting objectives. As you will see, there is no single "correct" or "best" solution to such problems. Indeed, there is a mathematical theorem about when there **cannot** be a best solution. However---and this may seem contractictory at first---some solutions are better than others. Mathematics also provides a framework for a systematic and documentable process which provides a role for the inevitable elements of human, subjective values.

First, we'll cover elementary mathematical principles that demonstrate both that there is no single "best" solution while yet allowing some solutions to be better than others. Important vocabulary here includes **"incommensuate"**, **dominating** and **non-dominating** solutions(along with **pareto optimality**), **decision frontier**, and **social utility function**.

Second, we'll briefly discuss some **heuristics** that people and groups often use, without necessarily realizing it, in solving multi-objective optimization problems. Awareness of such heuristics helps in identifying (often unstated) objectives implicit in the decision and enables you, by making them **explicit**, to clarify the problem and potentially open it up to useful discussion and **negotiation**. 

Later, we'll use the mathematics of **constraints** and **constraint functions** to support a process of rational decision making that nonetheless leaves space for subjectivity in valuing outcomes.



