---
id: "crow-swim-chair"
created: "Sun Oct  3 15:19:11 2021"
author: "Good Questions #13 and #14"
global_id: "8nfvTo"
---


```{r csc4-1, echo=FALSE, results="markup"}
askMC(
  "Which of the following is the reason that $\\displaystyle{\\lim_{x\\rightarrow 0}\\sin (1/x)}$ does not exist?",
  "+Because no matter how close $x$ gets to $0$, there are $x$'s near $0$ for which $\\sin(1/x) =1$, and some for which $\\sin (1/x)=-1$.+", 
  "Because the function values oscillate around $0$" = "They do oscillate. But oscillation is OK so long as the amplitude of the oscillation goes to zero.", 
  "Because $1/0$ is undefined." = "The point of defining something as a $\\lim_{x\\rightarrow 0}$ is to avoid setting the input exactly to 0.",
  "all of the above",
  random_answer_order = FALSE
)
```

```{r csc4-2, echo=FALSE, results="markup"}
askMC(
  "Does $\\displaystyle{\\lim_{x\\rightarrow 0}x^2\\sin (1/x)}$ exist? (Hint: A good way to check a limit $\\lim_{x\\rightarrow 0}$ is to graph the function in a small domain containing zero.)",
   "No,  because no matter how close $x$ gets to $0$, there are $x$'s near $0$ for which $\\sin(1/x) =1$, and some for which $\\sin (1/x)=-1$.",
  "No, because the function values oscillate around $0$.",
  "No, because $1/0$ is undefined.",
  "+Yes, it equals 0.+",
  "Yes, it equals 1.",
  random_answer_order = FALSE
)
```  
