---
id: "horse-understand-pants"
created: "Mon Oct  4 08:05:07 2021"
global_id: "LnfcbZ"
---

`r insert_calcZ_exercise("18.XX", "LnfcbZ", "Exercises/GoodQuestions/horse-understand-pants.Rmd")`

```{r hupv-1, echo=FALSE, results="markup"}
askMC(
  "Can a line be drawn that touches but does not cross the graph of the function $g(x) \\equiv |x|$ at $x=0$?",
  "Yes, but there is just one such line." = "A horizontal line $h(x) \equiv 0$ touches the graph but doesn't cross it. But you can rotate the line around the point (0,0) without crossing the graph so long as you don't give it a slope $\\geq 1$.",
  "Yes, but there are just two ways to do it.",
  "No, any line touching the graph of $g(x)$ at $x=0$ must cross it." = "A horizontal line $h(x) \equiv 0$ touches the graph but doesn't cross it.",
  "+There is an infinite number of such lines.+"
)
```
  
```{r hupv-2, echo=FALSE, results="markup"}
askMC(
  "What is the value of the function $\partial_x g(x)$ at $x=0$?",
  "`1",
  "0",
  "+1",
  "any of the above",
  "+none of the above+" = "NOT UNIQUE"
)


What's wrong with this statement? The derivative is the slope of the tangent line to a function.




