---
id: "seal-wake-bed"
created: "Sun Oct  3 16:18:17 2021"
global_id: "fiSV7o"
---



```{r swb7-1, echo=FALSE, results="markup"}
askMC(
  "What is the maximum number of **horizontal** asymptotes that a function can have?",
  "one",
  "+two+" = "Asymptotes are defined as the input goes to $\\infty$ and to $-\\infty$. Functions always have a unique output for any input, so the output can approach a value in only one way.",
  "three",
  "as many as you like",
  random_answer_order = FALSE
  )
```

```{r swb7-2, echo=FALSE, results="markup"}
askMC(
  "A function can cross its **horizontal** asymptote.",
  "+True+" = "",
  "False" = "Consider the constant function $g(x) = c$. The horizontal asymptote is $c$ in both directions. Now add a wave packet $f(x)$ to for $g(x) + f(x)$. This will cross $c$ several times, but the wave packet goes to zero as $x \\rightarrow \\pm \\infty$.",
  random_answer_order = FALSE
)
```

<!-- added by Daniel Kaplan -->
```{r swb7-3, echo=FALSE, results="markup"}
askMC(
  "What is the maximum number of **vertical** asymptotes that a function can have?",
  "one",
  "two",
  "three",
  "+as many as you like+" = "Here's a recipe for constructing a vertical asymptote. Take any well-behaved function $g()$ without any vertical asymptote. Now form $g(x)/\\left[(x-x_1)(x-x_2)\\cdots(x-x_n)\\right] ",
  random_answer_order = FALSE
)
```

<!-- added by Daniel Kaplan -->
```{r swb7-4, echo=FALSE, results="markup"}
askMC(
  "A function can cross its **vertical** asymptote.",
  "True" = "",
  "+False+" = "Think of the vertical asymptote as a vertical line. We know the function graph becomes tangent to this line as it reaches to $\\pm \\infty$. If the function had also crossed the line somewhere, the function would fail the vertical-line test; there would be input values near the line where the so-called \"function\" would take on two different values. Mathematical functions must always have a single output for any given input.",
  random_answer_order = FALSE
)
```
