---
title: "Graphs for constrained optimization"
author: "Daniel Kaplan"
output: pdf_document
---

```{r include=FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
f <- rfun( ~ x + y, seed=101)
g <- rfun( ~ x + y, seed=201)
h <- rfun( ~ x + y, seed=302)
dom <- domain(x=c(-3, 3), y=c(-3, 3))
contour_plot(f(x,y) ~ x + y, dom, skip=0) %>%
  contour_plot(g(x,y)  ~ x + y, filled=FALSE, 
               contours_at = 3, npts=300,
               contour_color="orange3", size=2, labels=FALSE) %>%
  contour_plot(h(x,y)  ~ x + y, dom, size=15, 
               contour_color="dodgerblue", alpha=0.1,
               contours_at = seq(-20, -11, length=60),
               labels=FALSE) %>%
  contour_plot(h(x,y)  ~ x + y, dom, size=3, 
               contour_color="dodgerblue", alpha=0.75,
               contours_at = -10,
               labels=FALSE) %>% 
  gf_labs(title="(A)")
```


```{r echo=FALSE, warning=FALSE, message=FALSE}
f <- rfun( ~ x + y, seed=221)
g <- rfun( ~ x + y, seed=331)
h <- rfun( ~ x + y, seed=312)
dom <- domain(x=c(-3, 3), y=c(-3, 3))
contour_plot(f(x,y) ~ x + y, dom, skip=0) %>%
  contour_plot(g(x,y)  ~ x + y, filled=FALSE, 
               contours_at = 0, npts=300,
               contour_color="orange3", size=2, labels=FALSE) %>%
  contour_plot(h(x,y)  ~ x + y, dom, size=15, 
               contour_color="dodgerblue", alpha=0.1,
               contours_at = seq(-20, -11, length=60),
               labels=FALSE) %>%
  contour_plot(h(x,y)  ~ x + y, dom, size=3, 
               contour_color="dodgerblue", alpha=0.75,
               contours_at = -10,
               labels=FALSE) %>% 
  gf_labs(title="(B)")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
f <- rfun( ~ x + y, seed=421)
g <- rfun( ~ x + y, seed=451)
h <- rfun( ~ x + y, seed=463)
dom <- domain(x=c(-3, 3), y=c(-3, 3))
contour_plot(f(x,y) ~ x + y, dom, skip=0) %>%
  contour_plot(g(x,y)  ~ x + y, filled=FALSE, 
               contours_at = 0, npts=300,
               contour_color="orange3", size=2, labels=FALSE) %>%
  contour_plot(h(x,y) +3  ~ x + y, dom, size=6, 
               contour_color="dodgerblue", alpha=0.1,
               contours_at = seq(14, 23, length=40),
               labels=FALSE) %>%
  contour_plot(h(x,y) +3  ~ x + y, dom, size=3, 
               contour_color="dodgerblue", alpha=0.75,
               contours_at = 14,
               labels=FALSE, filled=FALSE)%>% 
  gf_labs(title="(C)")
```
