---
title: "MMAC 1.2"
---

```{r include=FALSE, context="setup"}
library(etude2)
```

**Exercises 41-48**

Refer to the contour graph of function $f(x, y)$ on MMAC page 34 at the top of the right column.

```{r mmax-1-2-QA1, echo=FALSE}
etude2::etudeQ(
  prompt = "41) Find the value of $f(3,0)$.",
  1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, "+6+", 6.5,
  random_answer_order = FALSE
  )
```

```{r mmax-1-2-QA2, echo=FALSE}
etude2::etudeQ(
  prompt = "42) Find the value of $f(1, 3)$.",
  1, 1.5, 2, 2.5, 3, 3.5, "+4+", 4.5, 5, 5.5, 6, 6.5,
  random_answer_order = FALSE
  )
```

```{r mmax-1-2-QA3, echo=FALSE}
etude2::etudeQ(
  prompt = "43) At $(3, 0)$, does $f(x,y)$ immediately increase or decrease as the $x$-input increases?",
  "+decrease+", "increase",
  random_answer_order = FALSE
  )
```

```{r mmax-1-2-QA4, echo=FALSE}
etude2::etudeQ(
  prompt = "44) At $(1, 3)$, does $f(x,y)$ immediately increase or decrease as the $x$-input increases?",
  "decrease", "+increase+",
  random_answer_order = FALSE
  )
```

```{r mmax-1-2-QA5, echo=FALSE}
etude2::etudeQ(
  prompt = "45) At $(3, 0)$, does $f(x,y)$ immediately increase or decrease as the $y$-input increases?",
 "decrease", "+increase+",
  random_answer_order = FALSE
  )
```


```{r mmax-1-2-QA6, echo=FALSE}
etude2::etudeQ(
  prompt = "46) At $(1, 3)$, does $f(x,y)$ immediately increase or decrease as the $y$-input increases?",
  "decrease", "+increase+",
  random_answer_order = FALSE
  )
```

```{r mmax-1-2-QA7, echo=FALSE}
etude2::etudeQ(
  prompt = "47) Approximate the value and coordinates of the global **minimum** of $f(x, y)$",
    "$(x=1, y=2)$ with a value of 2."  = "",
    "+$(x=1, y=2)$ with a value between 1 and 2.+"  = "",
    "$(x=1, y=2)$ with a value of 0."  = "",
    "$(x=3, y=2)$ with a value of 5."  = "",
    "$(x=3, y=0)$ with a value between 5 and 6."  = "",
    "$(x=3, y=0)$ with a value between 6 and 7."  = "",
    "$(x=3, y=0)$ with a value of 7."  = "",
  random_answer_order = FALSE
  )
```

```{r mmax-1-2-QA8, echo=FALSE}
etude2::etudeQ(
  prompt = "48) Approximate the value and coordinates of the global **maximum** of $f(x, y)$",
  "$(x=1, y=2)$ with a value of  2." ,
    "$(x=1, y=2)$ with a value between 1 and 2." ,
    "$(x=1, y=2)$ with a value of 0.",
    "$(x=3, y=2)$ with a value of 5.",
    "$(x=3, y=0.5)$ with a value between 5 and 6.",
    "+$(x=3, y=0.5)$ with a value between 6 and 7.+",
    "$(x=3, y=0.5)$ with a value of 7.",
  random_answer_order = FALSE
  )
```

```{r mmax-1-2-QA9, echo=FALSE}
etude2::etudeQ(
  prompt = "Last one) Which is true of the region near $(x=3, y=3)$?",
    "It contains a global maximum."  = "",
    "It contains a global minimum."  = "",
    "It contains a local maximum."  = "",
    "+It contains a local minimum.+"  = "",
    "None of the above" = "",
    random_answer_order = FALSE
  )
```
