---
title: "Dimensions in formulas"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(etude2)
```

NEED TO INSERT THE FORMULAS from MMAC

For each mathematical operation, identify the operation as valid or invalid according to the rules of dimensional arithmetic.



```{r daily-digital-10-QA1, echo=FALSE}
etude2::etudeQ(
  prompt = "For Formula **25** on MMAC p. 259, choose which rule (if any) is violated.",
    "Addition or Subtraction rule" = "Both the numerator and denominator are valid subtractions, with dimension L and T respectively.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "There's no exponent here.",
    "+It's valid. No rules are violated.+" = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```


```{r daily-digital-10-QA2, echo=FALSE}
etude2::etudeQ(
  prompt = "For Formula **26** on MMAC p. 259, choose which rule (if any) is violated.",
    "Addition or Subtraction rule" = "No addition or subtraction here.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "There's no exponent here.",
    "+It's valid. No rules are violated.+" = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```

```{r daily-digital-10-QA3, echo=FALSE}
etude2::etudeQ(
  prompt = "For Formula **27** on MMAC p. 259, choose which rule (if any) is violated.",
    "Addition or Subtraction rule" = "No addition in this formula.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "+Exponential+" = "The  exponent is 4 ft /  3 g, which  has dimension L / M.  Exponents must *always* have dimension [1].",
    "It's valid. No rules are violated." = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```

```{r daily-digital-10-QA4, echo=FALSE}
etude2::etudeQ(
  prompt = "For Formula **28** on MMAC p. 259, choose which rule (if any) is violated.",
    "Addition or Subtraction rule" = "No addition or subtraction in this formula.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "The exponent is 4hr/3min,  which has dimension T/T = [1]. So the rule is satisfied.",
    "+It's valid. No rules are violated.+" = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```

```{r daily-digital-10-QA5, echo=FALSE}
etude2::etudeQ(
  prompt = "For Formula **29** on MMAC p. 259, choose which rule (if any) is violated.",
    "+Addition or Subtraction rule+" = "You can't subtract M from M$^2$. (Strictly speaking, lbs has dimension of force, $M L^2 / T^2$, but you can't subtract force from M$^2$ either.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "There's no exponent here.",
    "It's valid. No rules are violated." = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```

```{r daily-digital-10-QA6, echo=FALSE}
etude2::etudeQ(
  prompt = "For Formula **30** on MMAC p. 259, choose which rule (if any) is violated.",
    "+Addition or Subtraction rule+" = "You can't add L$^3$ to L$^2$.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "Maybe you're thinking that the cube-root rule is violated, but since the  quantity in the cube root is invalid, the root doesn't do anything additionally wrong.",
    "It's valid. No rules are violated." = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```
