---
title: "Dimensions of parameters"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(etude2)
```

```{r daily-digital-10-QA7, echo=FALSE}
etude2::etudeQ(
  prompt = "A) The dimension of $t$ is T,  that is, $[t] = T$. What must the dimension of $k$ for the arithmetic operation  to make sense?",
    "[1]"  = "Then $[kt] = $T, which  would violate the exponential rule.",
    "+T$^{\ -1}$+" = "Right, [k] needs to cancel out [t] so that the exponention is valid.",
    "T" = "Then $[kt] = $T$^2$, which  would  violate the exponential rule.",
    "None of the above"  = "",
  inline = FALSE
)
```

```{r daily-digital-10-QA8, echo=FALSE}
etude2::etudeQ(
  prompt = "B) What must the dimension of $c$ for the arithmetic operation $1 + c \\cdot 2^{kt}$  to make sense?",
    "+[1]+"  = "Right.  You're going to  have to add $c \\cdot 2^{kt}$ to 1. Since $[kt] = [1]$, $c$ also needs to be dimensionless.",
    "T$^{-1}$" = "",
    "T" = "Then $[kt] = $T^2$, which  would  violate the exponential rule.",
    "Depends on the dimension of  $2^{kt}$"  = "We already determined that $[kt]  = [1]$, so $[2^{kt}] = [1]$.",
  inline = FALSE,
  random_answer_order =  FALSE
)
```
