# Block 1: Functions

## M01 Course Introduction [Classroom]

Written Homework #1 (HW01) Assigned

Feedback01 Assigned

Reading

Welcome to Calculus

Chapter 1 - Change

Student Outcomes (read: “Be able to…”)

1. Access the course textbook

2. Access the course Teams channel

3. Access & submit assignments in Gradescope

4. Know the content of the course letter

5. Describe (in broad terms) the structure of the course [??? This isn't a student outcome, is it?]

6. Identify inputs and outputs of a function given in mathematical notation

    - VDKUI

7. Evaluate a function given in mathematical notation (e.g.,
$\text{line}(x) \equiv a x + b$)

8. Estimate (model) a rate of change using a line and the rise-over-run formula

    - KHDUE


### Instructor tips:

Prof. Schaubroeck used a very nice example to illustrate clearly two important points. 

    - She wrote on the board, without explanation, a formula $y = \frac{5}{9}[x-32]$ and asked students what this was. One student recognized it as the conversion from Fahrenheit to Celcius. Then she said, "Wouldn't this have been easier if I had written $\text{cel}(F) \equiv \frac{5}{9}[F - 32]$?"
    
    
    
    - One student said, "that's great. I hated all those greek letters."

Austin: imagine you're playing fantasy football with a pickup game with some professional athletes. A lot of athletes are in that middle and are equivalent statistically: Basketball: Martha and Betty are basically equivalent. It doesn't matter to you which one you have on the team, because they are equal. But they are fundamentally different people. 

    - Betty $\equiv$ From Illinois, great at layups and three-point shots. 
    - Martha $\equiv$ from CA, excellent at rebounds, great passer.
    
Austin: Asked "What's the input and what's the output?" $y = mx + b$ The input is $x$. Better to use $\equiv$. How about $m=\frac{y-b}{x}$. Here, $m$ just so happens to be equal to the relationship here. 

## M02 Functions as I/O and Models [Lectinar]

Reading

Chapter 2 – Modeling for Functions

Chapter 3 – Structure of a function

Section 5.6 – CalcZ Naming Conventions (Independent Reading)

Student Outcomes

1. Describe functions as a mapping from input(s) and to a corresponding output

2. Understand the Input/Output (I/O) correspondence as the mathematical model of a real-world phenomenon

3. Know the basic R syntax for multiplication, division, addition, subtraction, exponents and know how to evaluate functions in R

    - BXCA4
    - 3KEgLM
    - zSgXP2
    - VIW7T

4. Know (Distinguish between) the behaviors and R commands for the Pattern-book Functions (Exponential, Logarithm, Sinusoidal, Power family, Gaussian, Sigmoid)

    - H2KG3
    - Pdt9jy

5. Identify the Domain and Range (i.e., valid inputs and outputs) of the pattern-book functions

    - RLUCX
    - DLWSA
    - MNCLS2



## M03 Describing Functions [Lectinar]

Reading

Chapter 4 – Describing Functions

Chapter 5 – Notation for functions (sections 5.1-5.4 only)

Student Outcomes

1. Understand the various ways functions can be given: as Computer commands, Tables, and via word descriptions

2. Distinguish between a mathematical expression/function and the associated notation (e.g., $=$, $\equiv$, and `<-`)

3. Translate a function given in mathematical notation to R code and back

    - aeOnO5

4. Determine from a graph the concavity, inflection point(s), continuity, asymptotic behavior, periodic behavior, and local extreme points of a function

    - H2eu2
    - PYKG5

5. Reflexively apply the CalcZ naming conventions (covered in textbook, Chapter 5.6)

    - TKWEW
    - LDNE
    - kZG5Fj



## M04 Graphical representations for Single- and Multi-variate functions [Classroom]

Reading

Sections 5.5 & 5.7 – Notation for functions in R

Chapter 6 – Graphics & Function Graphs

Student Outcomes

1. Produce an R plot of a given function over a given graphics domain

2. Apply the `makeFun()` command in R to define a new function and assign it a name

3. Apply the pipe operator (`%>%`) to layer multiple graphics in one plot

4. Know the difference between a min/max and an argmin/argmax



## M5, Modeling with Parameterized Functions (Day 1) [Lectinar]

Quiz01 in-class Add questions to M4

Chapter 7 – Parameters for functions

Chapter 8.1 & 8.2 – Variations from Scaling & Curve fitting an exponential

Student Outcomes

1. Apply input scaling to the basic modeling functions

     - MWLCS
     - VcUetN
     - kUmsBG

2. Determine how input scaling was applied to a basic modeling function

     - uKCIE
     - BLECL
     - YLWP1

3. Know that exponential functions always have a constant doubling/halving time; use this property of exponentials to estimate the remaining/growth of a quantity after a given time

    - vkwl4
    - asevss

4. Estimate the parameters (A, k, t, B) for an exponential function given a dataset or graph

    - YLWP2



## M6: Modeling with Parameterized Functions (Day 2) [Classroom]


Chapter 8 – Process of modeling

Student Outcomes

1. Estimate the parameters for a periodic function (A, P, B, and t0) given a dataset or graph

    - YELXG
    - VBWD

2. Estimate the parameters for a Gaussian function (A, mean, sd) given a dataset or graph

    - IELWV

3. Estimate the parameters for a Sigmoidal function (A, mean, sd) given a dataset or graph

    - EKCIE (Needs rework)

4. Identify related/corresponding Gaussian and Sigmoidal functions

    - CKSLE


## M7 The Slope Function, Function Inverses, and “Solving” [Lectinar?]

Chapter 9 – The Slope Function

Chapter 10 – Function Inverses and “solving”

Student Outcomes

1. Understand that for a continuous function with a curved graph, if you zoom in closely around a given point, will look like a straight line

    - RDWKW (Move from Chapter 9 to Chapter 8)

2. Calculate the average/instantaneous rate of change for a given function in mathematical or R notation or estimate the same using a graph of the function

    - KEWIX
    - YQCLE
    - rTSX3
    - URIMX
    - HRTIX

3. Compare the rates of change of a functions or across different inputs of the same function

    - WRWIX
    - CUXLR

4. Use the guess and check method to estimate the inverse of a function for a particular input

    - WLDN1



## M8 Assembling Functions [Lectinar]

Chapter 11 - Assembling functions

Student Outcomes

1. Graphically construct a linear combination of two given functions

    - LDKKVA
    - AMBXI

2. Evaluate an assembled function

    - aA0ykt
    - fmwTFj

3. Assemble multiple modeling functions by combination, composition, and/or multiplication to match a given function or graph

    - FISHU

4. Decompose an assembled function into its constituent modeling functions and identify the combination, composition, and/or multiplication steps using during assembly

    - AVNOW
    - JWUVA
    - MWDKVA

## M9 Multivariate functions [Classroom]

Admin

Reading

Chapter 12 – Functions with Multiple Inputs

Student Outcomes

Be able to read a table representing of a multivariate function

ICLSE

Evaluate a function with multiple inputs

EDKKW

EDKYV (Remove – I’m not sure what this question is getting at)

Read and construct (in R) surface plots

dB1r5F Move from Chapter 6 to Chapter 11

Read and construct (in R) contour plots

drawing (Move from Chapter 6 to Chapter 11)

daylength (Move from Chapter 6 to Chapter 11)

Sketch (by hand) a slice plot of a multivariate function

Estimate if slope in a particular direction is positive or negative



## M10 Iterative Modeling & the modeling cycle [Lectinar]

Admin

Quiz02 in-class [Add drill to M9]



Chapter 13 – Piecewise Functions (Independent Reading)

Chapter 14 – Modeling Cycle

Student Outcomes

1. Understand how ifelse() is used to define a piecewise function in R

2. Describe the difference between two given models

3. Identify the disagreements between a model and a given dataset

    - GSEww

## M11 Magnitudes: Semi-log & Log-log plots (Day 1) [Lectinar]


Chapter 15 - Magnitudes

Student Outcomes

1. Know and reflexively apply the properties of logarithms and exponentials

    - ILESX
    - TLCIX

2. Be able to read a semi-log or log-log plot

    - j3xe
    - ILXEG
    - EWLCI
    - ILEXE
    - SELIX

3. Estimate parameters for an exponential & power function using a semi-log or log-log plot

    - RWESX



## M12 Catchup Day [Classroom]



## M13 Dimensional Analysis [Lectinar]


Chapter 16 - Dimensions

Student Outcomes

1. Use identities to convert between units

2. Know the definition of fundamental and derived dimensions

3. Use dimensional arithmetic to determine the dimension of various combinations of physical quantities

4. Be able to identify valid or invalid operations based on the involved quantities’ dimensions

    - UGDKY

5. Use dimensional analysis to solve for the dimension of unknown constants or quantities

6. Understand the general idea of using dimensional analysis to develop reasonable relationships between physical quantities




## M14 GR1 Review Day [Lectinar]


## M15 GR1 [TBD]


## M16 Project1 [Classroom]

RDTTKW This is the Satellite project form last year. It's in the file with this global-id. Figure out what format to put it in and put it up.
