---
title: "Chain of differentiation"
date: "MMM DD YYYY"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r include=FALSE}
library(gradethis)
library(mosaic)
knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60,
                 exercise.checker = gradethis::grade_learnr)
```

Here are several functions that are related by differentiation and integration:

a. $\frac{1}{a} e^{ax + b}$
b. $a^2 e^{a x + b}$
c. $\frac{1}{a^2} e^{ax + b}$
d. $e^{ax + b}$
e. $a e^{ax + b}$

```{r chain1}
askMC(
  prompt = "Which is the correct order of the functions so that the derivative of each function is to the left and the anti-derivative to the right?",
  "+BEDAC+",
  "BDECA" = "$\\frac{1}{a^2} e^{a x + b}$ is the anti-derivative of $\\frac{1}{a} e^{ax + b}$.",
  "BDCEA" = "Hint: The multipliers (e.g. $a^2$ or $\\frac{1}{a^2}$) should be in a particular, simple sequence.",
  "EBDCA",
  "EBDAC" = "$a^2 e^{a x + b}$ is the derivative of $a e^{a x + b}$."
)
```

Here are several functions that are related by differentiation and integration:

a. $-\cos(x)$
b. $\cos(x)$
c. $\sin(x)$
d. $-\sin(x)$

```{r chain2}
askMC(
  prompt = "Which is the correct order of the functions so that the derivative of each function is to the left and the anti-derivative to the right?",
  "ABDC" = "Consider that anti-differentiation or differentiation always caused the type of trig function to change.",
  "BDCA" = "Consider that anti-differentiation or differentiation always caused the type of trig function to change.",
  "DBAC" = "Consider that anti-differentiation or differentiation always caused the type of trig function to change.",
  "+ADBC+",
  "BADC" = "Consider that anti-differentiation or differentiation always caused the type of trig function to change."
)
```
