---
title: "Daily Digital 25"
subtitle: "Math 142Z"
output: learnr::tutorial
runtime: shiny_prerendered
---


```{r mother1-setup, include=FALSE}
# Calculus/graphics/data packages
library(mosaic)
library(mosaicCalc)
library(ggformula)
library(DT)
knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```


```{r context="setup", include=FALSE}
### Boilerplate: Packages relating to `{learnr}` and 
### submission functionality.
etude2::load_learnr_safely()
library(gradethis)
library(etude2)
library(learnrhash)
library(mosaic)
library(mosaicCalc)
library(math141Z)
```


```{r context="setup", include=FALSE}
# Good practice to include these in any document bringing
# with the answer submission system
etude2::set_master_id("DD-24") # Add the DD number
etude2::etude_document_name("DD-142Z-24") # Add the DD number
# Fill this data frame in when document is completed. See etude2 documentation
document_roster <- tibble::tribble(
  ~ id,
)
```

```{r eval=FALSE}
# Leave this safety check here
if (etude2::etude_document_name() == "DD-") 
  stop("You must set the master_id() and the document name specifically and uniquely for this document")
```

## Objectives




## Hand in your work

<div style="color: red;">USAFA CalcZ students should hand in their work via GradeScope</div>

<!--

REMEMBER: Press the REFRESH button before copying the hash code and submitting it at the <a href="https://forms.microsoft.com/Pages/ResponsePage.aspx?id=Bgq4einwwEWE0X2tGc48YcCKijCKVrhDla481YPh1UJUMVdERUtVT0VOSEpMMEdPQU1aWlpYTTA0RS4u" target = "_blank">USAFA Math 142Z site</a>


```{rr echo=FALSE, messages=FALSE}
etude2::submissions_ui()
```

```{rr context="server", echo=FALSE, messages=FALSE}
etude2::submissions_logic()
```

-->

-----

Location: `r gsub("^.*USAFA/", "", knitr::current_input(dir = TRUE))` `r  etude2::etude_document_name()`

