---
title: "Quiz 5"
author: "Daniel Kaplan"
runtime: shiny_prerendered
output: learnr::tutorial
---

```{r include=FALSE}
etude2::load_learnr_safely()
library(etude2)
```

```{r q5-1, echo=FALSE, results="markup"}
etude2::etudeQ(
  "Suppose matrix ${\\mathbf A} = \\left[\\begin{array}{r}1 & 2 \\\\4 & -1 \\end{array}\\right]$ and ${\\mathbf X}=\\left[\\begin{array}{rr}-1\\\\2  
\\end{array}\\right]$. Is vector ${\\mathbf X}$ an eigenvector for ${\\mathbf A}$?",
"+Yes+",
"No",
"Not enough information is given",
random_answer_order = FALSE
)
```

```{r q5-2, echo=FALSE, results="markup"}
etude2::etudeQ(
  "Suppose ${\\mathbf B}$ is a $2 \\times 2$ matrix that gives a dynamical system: ${\\mathbf X}_{n+1}=B{\\mathbf X}_n$. 
  
  If ${\\mathbf X}_0=\\left (\\begin{matrix}24 \\\\ 16\\end{matrix} \\right )$ is an Eigenvector of ${\\mathbf B}$ with corresponding Eigenvalue $\\lambda=1/2$, then what is ${\\mathbf X}_2$?",
"$\\left (\\begin{matrix}48 \\\\ 32\\end{matrix} \\right )$",
"$\\left (\\begin{matrix}12 \\\\ 8\\end{matrix} \\right )$",
"+$\\left (\\begin{matrix}6 \\\\ 4\\end{matrix} \\right )$+",
"$\\left (\\begin{matrix}3 \\\\ 2\\end{matrix} \\right )$",
random_answer_order = FALSE
)
```


```{r q5-3, echo=FALSE, results="markup"}
etude2::etudeQ(
  "If the initial state of a linear dynamical system is an Eigenvector, then the trajectory associated to that initial state is ...?",

"An unstable fixed point",
"A curving path",
"+A straight line path+",
"A stable fixed point",
"Oscillatory",
random_answer_order = FALSE
)
```

```{r q5-4, echo=FALSE, results="markup"}
etude2::etudeQ(
  "Which of the following differential equations represents the statement: *\"The rate at which the radioactive substance decays is directly proportional to the amount of substance remaining.\"*",
"$\\dot {x} =Ce^{-kt}$",
"$x(t)=Ce^{-kt}$",
"+$\\dot x=-kx$+",
"$\\dot x=-k(x-x_0)$",
"$\\dot x = \\int x dx$",
random_answer_order = FALSE
)
```

```{r q5-5, echo=FALSE, results="markup"}
etude2::etudeQ(
"Suppose you pull the roast out of the oven when its temperature is 175$\\degree$F.  The room temperature is 70$\\degree$F and the roast cools in accordance with Newton’s Law of Cooling.  Let $y(t)$ be the temperature of the roast $t$ minutes after it is removed from the oven. Which of the following is the differential equation that models this situation?",

"+$\\dot y = -k(y-70)$+",
"$\\dot y = -k(y-175)$",
"$\\dot y = 175e^{-kt}-70$",
"$\\dot y = -ky$",
"$y(t)=Ce^{-kt}+175$",
random_answer_order = FALSE
)
```

```{r q5-6, echo=FALSE, results="markup"}
etude2::etudeQ(
"Let $\\dot{x} = g()$ be some differential equation. Suppose that the general solution to it is $x(t)=\\frac{1}{t+C}$. If $x(0)=2$, then what is the value of $C$ ?", 
"2",
"0",
"1",
"+$\\frac{1}{2}$+",
"Cannot be determined",
random_answer_order = FALSE
)
```

```{r q5-7, echo=FALSE, results="markup"}
etude2::etudeQ(
"Given the equation $\\dot{x} = -\\frac{1}{3}x$, which of the following functions are solutions:

a. $x(t)=4e^{-t/3}$    
b. $x(t)=e^{-t/3}+C$    
c. $x(t)=e^{-t/3}$    
d. $x(t)=e^{-x/3}$    
e. None of these are solutions    

",
"a & b",
"+a & c+",
"b & d",
"a & d",
"e",
random_answer_order = FALSE
)
```

```{r q5-8, echo=FALSE, results="markup"}
etude2::etudeQ(
  "Given $\\dot x =0.2x(1-\\frac{x}{50})$ with initial condition $x(0)=70$, is $x(t)$ increasing, decreasing, constant, or cannot be determined?",
"Increasing",
"+Decreasing+",
"Constant",
"Cannot be determined",
random_answer_order = FALSE
)
```
