---
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r include=FALSE}
etude2::load_learnr_safely()
library(gradethis)
library(mosaic)
knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```

```{r context="setup"}
## SET UP THE PROBLEM HERE. 
# Note use of double \\ for latex in quotation marks
problemLatex <- "\\int  A \\sin(Bt + C) + D\\ dt?"
answer_fun <- function(t,A,B,C,D) -(A/B)*cos(B*t + C) + D*t
evaluate_at <- 1:10
correct_arguments <- c("t", "A", "B", "C", "D")
## Remember to set the CHUNK NAMES to match the file name
```

You may think that you have seen this problem earlier in this Daily Digital, but you have not.  Work out this anti-derivative on paper. 

<div style="font-size: 40px; text-align:center;">$`r problemLatex`$ </div>

Once you have your result, translate it into a correct R *function*. 

```{r IOD-EYE, exercise=TRUE, exercise.lines=5, exercise.cap="Integral of the day"}
F <- makeFun(  ~ t)
```

```{r IOD-EYE-check}
library(magrittr)
gradethis::grade_result(
  fail_if( ~ !is.function(.result), message = "Your result should be in the form of a function."),
  fail_if( ~ "x" %in% names(formals(.result)), 
           message = "How did an $x$ get into your answer?"),
  fail_if( ~ !all(correct_arguments %in% names(formals(.result))),
           message = "You don't seem to have the right argument name."),
  pass_if( ~ all(.result(t=1:10, A=1,B=2,C=3, D=4) ==
                          answer_fun(t=1:10, A=1,B=2, C=3, D=4)),
           message="In the GradeScope system that we are about to switch to for handing in answers, you will be asked to give a codeword to signify that you have found the correct answer. The codeword for this problem is **lift/drag**."),
  fail_if( ~ TRUE, message="Correct arguments, but not the right function.")
)  
```


