---
title: "Bessel radius"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(rlang)
library(mosaic)
library(mosaicCalc)
library(math141Z)
library(etude2)
```

```{r}
bessel <- function(x, k=5) {
  k = 0:k
  bcoef <- sapply(k, bessel_coef)
  basis_funs <- outer(x, k, "^")^2
  4 * basis_funs %*% cbind(bcoef)
}


bessel_coef <- function(k) {
  (-1)^k / ( (2^(2*(k+1))) * factorial(k)^2 )
}
```

```{r}
slice_plot(bessel(x, k=11) ~ x, domain(x=c(-10,10)), npts=500) 
```

Compare on domain [-3, 3] 1, 2, 3, 4, 5 order  to 20th order

Expand domain until dog runs after squirrel. 

Expand order to make the domain as wide as possible. 

- Underflow of coefficients
- Numerical noise at ends of domain whenever coefficients get low


## Gaussian

1. Derive the first, second, third, and fourth derivatives

```{r}
gauss_n <- function(n) {
  if (n==0) 1/sqrt(2*pi)
  else if (n %% 2) 0
  else (-1)^(n/2) / (prod(seq(2, n, by=2)) * sqrt(2*pi))
}

approx_gauss <- function(x, nmax) {
  res <- gauss_n(0)
  for (k in 2*rlang::seq2(1, nmax/2)) {
    res <- res + gauss_n(k) * x^k
  }
  res
}

integrate_gauss <- function(x, nmax) {
  res <- gauss_n(0) * x
  for (k in 2*rlang::seq2(1, nmax/2)) {
    res <- res + gauss_n(k) * x^(k+1) / (k+1)
  }
  res
}

```


```{r}
slice_plot(approx_gauss(x, 40) ~ x, domain(x=c(-4,4)))
slice_plot(integrate_gauss(x, 10) ~ x, domain(x=c(-3,3)))
```


