---
id: "mag-blue"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
```

::: {.scaffolding}
```{r results="hide"}
gf_point(BHP ~ displacement, data = Engines) %>%
  gf_refine(scale_x_log10(), scale_y_log10())
```
:::

Based on the log-log plot of horsepower (`BHP`) versus engine displacement, answer these questions.

```{r daily-digital-04-QA3, echo=FALSE}
askMC(
  prompt = "How many engines have a displacement of 1 liter or less?",
    "none" = "Perhaps you recognized that the left-most tick mark corresponds to a value of 1, and that no data points are 1 or smaller. But one liter corresponds to 1000 cc.",
    "7" = "This is the number of engines with displacement of 10 cc or smaller. But one liter corresponds to 1000 cc.",
    "+14+" = "Right. It's the $10^3$ tick that marks 1 liter, since 1 liter is 1000 cc.",
    "25" = "That would be true if the cut-off were 10 liters. But it's not.",
  randomAnswerOrder = FALSE
)
```

```{r daily-digital-04-QA4, echo=FALSE}
askMC(
  prompt = "Using the log-log plot, how many decades of BHP are spanned by the data?",
     "4" = "Not a bad answer, but not the best one either. Notice that the smallest engine is about half a decade below 1 BPM, and the largest is  about half a decade above 10,000 BPH",
    "+5+" = "",
    "100" = "The number $10^{100}$ is called a *googol* and is roughly how many particles (including photons, neutrinos, etc.)  are in the universe. Imagine,  quite contrary to fact, that 1 BHP could be generated by burning one molecule of fuel per second. Then as many fuel molecules as there are particles in the universe would have  to  be burned each second to power an engine at the high end of a span of 100 decades.",
  random_answer_order = FALSE
)
```

