---
id: "naked-zeros"
author: "Daniel Kaplan"
---

::: {.scaffolding}
Copy and paste the R/mosaic commands below in a `r sandbox_link()` and run the commands. ("Run code")
```{r results="hide"}
slice_plot(exp(x) ~ x, domain(x=c(-3, 3)))
```
The function's graph should result. To modify the command to draw another function, replace the `exp(x)` with another formula, e.g. `1/x`, 

:::

You are to look at the graph and and observe two features: whether the graph has a slope that is consistently positive or negative, and whether the function being graphed is concave up, concave down, neither, or concave up in some regions of the domain and down for others.

Make a list of the naked modeling functions. For each function in the list, say whether the function crosses zero, touches zero but doesn't cross, or doesn't touch at all in the part of the domain shown in the graphic: $-3 \leq x \leq 3$. Also note if the value of the function appears to be reaching a horizontal asymptote at zero for very negative $x$, for very positive $x$, for both, or neither.

We'll show you the answers for the exponential function. You'll have to modify the computer command to graph the other naked modeling functions.

function name | R formula  | slope         | concavity
--------------|------------|---------------|--------------
exponential   | `exp(x)`   | up            | concave up 
logarithm     |
sinusoid      | `sin(x)`   | both          | both
square        |
proportional  |
constant      |
reciprocal    |
hump          |
sigmoid       |


