---
id: "pattern-book-range"
author: "Daniel Kaplan"
---

A function's ***domain*** is the set of possible inputs to the function. A functions ***range*** is the set of possible outputs. For each of the pattern-book functions, specify what is the domain.

```{r nrlp2-1, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **exponential** function?",
  "+All positive outputs+", "All negative outputs", 
  "The whole number line", "A closed, finite interval of possibilities",
  random_answer_order = FALSE
)
```

```{r nrlp2-2, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **sine** function?",
  "All positive outputs", "All negative outputs", 
  "The whole number line", "+A closed, finite interval of possibilities+" = "Yes. The output of pattern-book sinusoid functions is always in the interval from -1 to 1, inclusive",
  random_answer_order = FALSE
)
```

```{r nrlp2-3, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book logarithm function?",
  "All positive outputs", "All negative outputs", 
  "+The whole number line+", "A closed, finite interval of possibilities",
  random_answer_order = FALSE
)
```

```{r nrlp2-4, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **square** function?",
  "+All positive outputs+", "All negative outputs", 
  "The whole number line", "A closed, finite interval of possibilities",
  random_answer_order = FALSE
)
```

```{r nrlp2-5, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **proportional** function?",
  "All positive outputs", "All negative outputs", 
  "+The whole number line+", "A closed, finite interval of possibilities" = "Yes. The output of pattern-book sinusoid functions is always in the interval from $-1 \\leq \\sin(x) \\leq 1$.",
  random_answer_order = FALSE
)
```

```{r nrlp2-6, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **sigmoid** function?",
  "All positive outputs", "All negative outputs", 
  "The whole number line", "+A closed, finite interval of possibilities+" = "Right. The pattern-book sigmoid function has an output that is always in the interval $0 < \\pnorm(x) < 1$.",
  random_answer_order = FALSE
)
```




