---
id: "scale-input-2"
author: "Daniel Kaplan"
global-id: "BLECL"
---

```{r include=FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
```

Find the straight-line function that will give the value on the black scale for each point $x$ on the blue scale. The function will take the blue-scale reading as input and produce the black-scale reading as output, that is:
$$\text{black}(x) \equiv a (x - x_0)$$

```{r echo=FALSE}
add_scale(exp(x) ~ x, domain(x=c(-2,2)), 3, 0) %>% 
  gf_labs(title="Graph (A)")
add_scale(pnorm(x) ~ x, domain(x=c(-3, 3)), -1.5, 0) %>% 
  gf_labs(title="Graph (B)")
add_scale(dnorm(x) ~ x, domain(x=c(-3, 3)), 2, -1) %>% 
  gf_labs(title="Graph (C)")
add_scale(pnorm(x) ~ x, domain(x=c(-3, 3)), 1.5, 2) %>% 
  gf_labs(title="Graph (D)")
```

```{r sc-in-2-A, echo=FALSE, results="markup"}
askMC(
  "For Graph A, which function maps blue $x$ to the value on the black scale?",
  "+$black(x) \\equiv x/3$+",
  "$black(x) \\equiv 3\\, x$" = "You're going the wrong way, from black to blue.",
  "$black(x) \\equiv x + 3$" = "Is there a horiztontal shift?",
  "$black(x) \\equiv x - 3$" = "Is there a horizontal shift?"
)
```

```{r sc-in-2-B, echo=FALSE, results="markup"}
askMC(
  "For Graph B, which function maps blue $x$ to the value on the black scale?",
  "+$black(x) \\equiv -2\\,x/3$+",
  "$black(x) \\equiv 3\\, x/2$" = "Look carefully at the $\\pm$ signs on the scales.",
  "$black(x) \\equiv 2\\,x/3$" = "Look carefully at the $\\pm$ signs on the scales.",
  "$black(x) \\equiv -3\\,x/2$" = "You're going the wrong way, from black to blue."
)
```

```{r sc-in-2-C, echo=FALSE, results="markup"}
askMC(
  "For Graph C, which function maps blue $x$ to the value on the black scale?",
  "+$black(x) \\equiv (x - 2)/2$+" = "Good. An interval of length 4 on the blue scale (say, from 2 to 6) becomes an interval of length 2 on the black scale. So you know that blue to black involves dividing by 2.",
  "$black(x) \\equiv 3\\, x$" = "Is there a shift",
  "$black(x) \\equiv 2\\,x$" = "Is there a shift?",
  "$black(x) \\equiv 2\\,(x + 2)$" = "You're going the wrong way, from black to blue."
)
```

```{r sc-in-2-D, echo=FALSE, results="markup"}
askMC(
  "For Graph D, which function maps blue $x$ to the value on the black scale?",
  "+$black(x) \\equiv 2 (x + 3)/3$+",
  "$black(x) \\equiv 3 (x - 3)/2x$",
  "$black(x) \\equiv 3 (x+1)/2$",
  "$black(x) \\equiv 3(x - 2)/2$" = "You're going the wrong way, from black to blue."
)
```
