---
title: "Graph-anti"
date: "MMM DD YYYY"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r include=FALSE}
etude2::load_learnr_safely()
library(gradethis)
library(etude2)
library(shiny)
knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60,
                 exercise.checker = gradethis::grade_learnr)
```

```{r context="setup", include=FALSE}
library(mosaic)
library(mosaicCalc)
```


The top graph shows a function $f(t)$. 

Answer the following questions about the anti-derivative $$F(t)$$ where $$F(t) \equiv \int f(t) dt$$

You can make measurements by *click/dragging* the mouse on the bottom graph.

```{r}
plotOutput("littlef", 
           brush=brushOpts("Fbrush", direction="x", fill=NA, stroke="orange", opacity = 1),
           height="250px")
h5("Stats on F() for orange lines")
htmlOutput("boxstats")
```

```{r context="server"}
f_seed <- reactiveVal(101)
f_function <- reactive({
  mosaic::rfun( ~ t, seed = f_seed())
})

output$boxstats <- renderText({
  if (is.null(input$Fbrush)) return("Drag mouse on graph to measure")
  width  <- input$Fbrush$xmax - input$Fbrush$xmin
  f <- f_function()
  F <- antiD(f(t) ~ t)
  yvals <- F(c(input$Fbrush$xmin, input$Fbrush$xmax))
  deltaF <- diff(yvals)
  glue::glue(
    "<p>Left: {signif(input$Fbrush$xmin,3)}      Right: {signif(input$Fbrush$xmax, 3)}      Width: {signif(width,3)}</p>
    <p>F(left): {signif(yvals[1], 3)}       F(right): {signif(yvals[2], 3)}       ∆F: {signif(deltaF,3)}</p>
    <p>Slope of F(): {signif(deltaF/width, 3)} </p>"
  ) %>% HTML()
})

output[["littlef"]] <- renderPlot({
  f <- f_function()
  
  suppressWarnings({
    P <- slice_plot(f(t) ~ t, domain(t=c(-5, 5))) %>%
      gf_hline(yintercept = 0, color="dodgerblue") %>%
      gf_labs(y = paste("f(t) for seed", input$seed),
              title = "f(t), the derivative of F(t)") %>%
      gf_refine(scale_x_continuous(breaks = (-5):5))
  })
  if (! is.null(input$Fbrush)) {
    Area <- tibble(
      t = seq(input$Fbrush$xmin, input$Fbrush$xmax, length=100),
      y = f(t)
    )
    Neg_area <- Area %>% filter(y < 0)
    P <- P %>% gf_ribbon(0 + y ~ t, data = Area, inherit=FALSE,
                         fill = "dodgerblue", color=NA, alpha = 0.3) 
    if (nrow(Neg_area) > 0)
      P <- P %>%
      gf_ribbon(0 + y ~ t, data=Neg_area %>% filter(y < 0), inherit = FALSE,
                fill = "orange3", color = NA, alpha = 0.3)
  }
  P
})

```

----

```{r context = "server"}
f_seed <- reactiveVal(864)
```

```{r GAD1}
askMC(
  "At which of the following values of t does $F(t)$ have a positive slope?",
  "-3"="Remember what $f(t)$ tells you about $F(t)$",
  "0"="Remember what $f(t)$ tells you about $F(t)$",
  "+3+",
  random_answer_order = FALSE
)
```

```{r GAD2}
askMC(
  "At which of the following values of t is $F(t)$ concave down?",
  "+-3+",
  "0"="Remember what $f(t)$ tells you about $F(t)$",
  "3"="Remember what $f(t)$ tells you about $F(t)$",
  random_answer_order = FALSE
)
```

```{r GAD3}
askMC(
  "Which of the following statements about $F(t)$ is true at the point t=3.5?",
  "There is a maximum value at this point"="This is true about $f(t)$ not $F(t)$",
  "The slope changes from positive to negative"="This is true about $f(t)$ not $F(t)$",
  "+The concavity changes from concave up to concave down+",
  random_answer_order = FALSE
)
```
