---
output: learnr::tutorial
runtime: shiny_prerendered
params:
  prefix: DD-03
  docname: "DD-142Z-03"
  title: "Daily Digital 03"
  subtitle: "Math 142Z"
  
title: "`r params$title`"
subtitle: "Math 142Z"
---

<!-- SET THE ABOVE prefix AND docname to be unique in the series of DDs -->

```{r mother1-setup, include=FALSE, messages=FALSE}
# Calculus/graphics/data packages
library(mosaic, quietly=TRUE)
library(mosaicCalc, quietly=TRUE)
library(ggformula, quietly=TRUE)
library(math141Z, quietly=TRUE)
library(DT, quietly=TRUE)

.prefix <- params$prefix
.docname <- params$docname
knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```



```{r context="setup", include=FALSE, messages=FALSE}
etude2::set_master_id("DD-03") # Add the DD number
etude2::etude_document_name("DD-142Z-03") # Add the DD number
# Fill this data frame in when document is completed. See etude2 documentation
document_roster <- tibble::tribble(
  ~ id,
)
```

<!-- END OF BOILERPLATE -->


## Accumulating change

```{r child="sailing-over-time.Rmd"}
```


## Power and energy

```{r child="solar-example.Rmd"}
```



## Algebraic Integral of the Day

```{r child="IOD-C.Rmd"}

```

## Careful with units!

```{r child="falcon-tell-mug.Rmd"}
```

## Hand in your work

REMEMBER: Press the REFRESH button before copying the hash code and submitting it at the <a href="https://forms.microsoft.com/Pages/ResponsePage.aspx?id=Bgq4einwwEWE0X2tGc48YcCKijCKVrhDla481YPh1UJUMVdERUtVT0VOSEpMMEdPQU1aWlpYTTA0RS4u" target = "_blank">USAFA Math 142Z site</a>


```{r echo=FALSE, messages=FALSE}
etude2::submissions_ui()
```

```{r context="server", echo=FALSE, messages=FALSE}
etude2::submissions_logic()
```

-----

Location: `r gsub("^.*USAFA/", "", knitr::current_input(dir = TRUE))` `r  etude2::etude_document_name("142Z-DD-03.Rmd")`

