---
title: "COVID air flow"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(mosaic)
library(mosaicCalc)
library(etude2)
```

Public health officials issue recommendations to help avoid epidemics and, when one occurs, to mitigate their spread. The preventive actions are embedded in vaccine recommendations and requirements, food safety protocols for processors and restaurants, and even in building and occupancy codes, particularly in the HVAC (heating, ventilation, air conditioning) standards that building inspectors are empowered to enforce. 

The COVID-19 pandemic points to a massive insufficiency of HVAC standards. This is not a criticism of those standards. Greater HVAC efficiency has substantial costs; designing optimal systems almost always involves a trade-off of benefits and costs.

For students and teachers, the HVAC-related COVID change that's most visible is the reduction in allowed occupancy and the physical distancing of desks, etc. The six-foot rule was proposed in 1897 by a German bacteriologist, Carl Flügge. His focus was on the spread of visible fluid droplets. Scientifically, this rule is obsolete. The earliest hints of the existence of viruses were in the 1890s, and, as we know now, COVID is spread largely by minuscule, invisible particles with the infectious agent being invisible even under the microscopes of bacteriologists.

Let's look at some modern work to understand the physics of airborne transmission and to evaluate possible interventions to reduce it. This is reported [here, in the New York Times](https://www.nytimes.com/interactive/2021/02/26/science/reopen-schools-safety-ventilation.html), in an easy to read and graphically compelling story. One video from the story is reproduced below. It's a complex visualization that is built up, one step at a time in the Times article.

<video width="480" height="360" controls>
  <source src="www/92072_1_classroom-covid-hp-promo_wg_720p.mp4" type="video/mp4">
</video>

The tool behind such research is ... you guessed it ... differential equations. The particular differential-equation model involved is called the Navier-Stokes equation, invented in 1822. Unlike the linear differential equations we are studying, there is no *ansatz*, and massive computational resources are routinely expended to find an approximate solution that applies in a setting of interest. Here, that setting is a conventional classroom.

The flow fields display in the research graphics is fundamentally the same as those we will use in this section of CalcZ. As always, since their invention by Newton, differential equations play a fundamental role in science.

It may seem overkill to use the apparatus of the Navier-Stokes equation to come to the sensible conclusion, "Open the window, please." But details matter, such as the location of the air filter in the classroom or the use of an out-blowing fan. 

The numerical solution to the equations in this example uses a state of tens of millions of numbers. But understanding differential equations can start with something as simple as a two-dimensional state.


