---
title: "More lambdas"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
library(math141Z)
```


```{r clock1-1, echo=FALSE, results="markup"}
etude2::etudeQ(
  "Consider the system $x_{n+1} = -1.2 x_n + 0.6 x_{n-1}$. What are the corresponding values of $\\lambda_{1,2}$? (Note, it doesn't matter which one you call $\\lambda_1$ and which one $\\lambda_2$. We've called the smaller of the two $\\lambda_1$.)",
  "+$\\lambda_1 = -1.60$ and $\\lambda_2 = 0.38$+",
  "$\\lambda_1 = 1.40$ and $\\lambda_2 = 1.83$",
  "$\\lambda_1 = -0.58$ and $\\lambda_2 = 1.40$",
  "$\\lambda_1 = -1.58$ and $\\lambda_2 = 1.40$"
)
```

```{r clock1-2, exercise=TRUE, exercise.cap="Sandbox", exercise.nlines= 5, eval=FALSE}

```

```{r clock1-3, echo=FALSE, results="markup"}
etude2::etudeQ(
  "Considering the value of $\\lambda_1$ in the correct answer to the previous question, what will the solution $x_n = x_0 \\lambda_1^n$ look like?",
  "A steady exponential growth away from $x=0$.",
  "A steady exponential decay to about $x=0$.",
  "An oscillating exponential decay to $x=0$.",
  "+An oscillating exponential growth away from $x=0$.+",
  random_answer_order = FALSE
)
```

```{r clock1-4, echo=FALSE, results="markup"}
etude2::etudeQ(
  "Considering the value of $\\lambda_2$ in the correct answer to the previous question, what will the solution $x_n = x_0 \\lambda_1^n$ look like?",
  "A steady exponential growth away from $x=0$.",
  "+A steady exponential decay to about $x=0$.+",
  "An oscillating exponential decay to $x=0$.",
  "An oscillating exponential growth away from $x=0$.",
  random_answer_order = FALSE
)
```

