---
title: "Integral of the day: TEMPLATE"
date: "MMM DD YYYY"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(gradethis)
library(mosaic)
knitr::opts_chunk$set(echo = FALSE)
learnr::tutorial_options(exercise.timelimit = 60, 
                 exercise.checker = gradethis::grade_learnr)
```

```{r context="setup"}
## SET UP THE PROBLEM HERE. 
# Note use of double \\ for latex in quotation marks
problemLatex <- "\\int at + v_0 dt"
answer_fun <- makeFun(a*t^2/2 + v0 *t ~ t)
evaluate_at <- 1:10
correct_arguments <- c("t")
## Remember to set the CHUNK NAMES to match the file name
```

Work out this anti-derivative on paper.

<div style="font-size: 40px; text-align:center;">$`r problemLatex`$ </div>

Once you have your result, translate it into a correct R *function*. Use the computer name `v0` for the mathematical symbol $v_0$.

```{r IOD-A, exercise=TRUE, exercise.lines=5, exercise.cap="Integral of the day"}
F <- makeFun()
```

```{r IOD-A-check}
library(magrittr)
gradethis::grade_result(
  fail_if( ~ !is.function(.result), message = "Your result should be in the form of a function."),
  fail_if( ~ !all(correct_arguments %in% names(formals(.result))),
           message = "You don't seem to have all the right argument names."),
  pass_if( ~ all(.result(evaluate_at, 3, 12) ==
                          answer_fun(evaluate_at, 3, 12))),
  fail_if( ~ TRUE, message="Correct arguments, but not the right function.")
)  
```


Now that you have the correct answer, use Latex to typeset the formula in the function here. Some Latex tips: `v_0` will produce $v_0$, while `\frac{1}{2}` will produce $\frac{1}{2}$.

```{r results="asis"}
etude2::latex_entry_box("latex-E")
```

```{r context="server"}
id <- "latex-E"
answers <- c("a t^2 / 2 + v_0 t", "a t^2 / 2 + v_0 t + C",
             "\\frac{1}{2} a t^2 + v_0 t", "\\frac{1}{2} a t^2 + v_0 t + C",
             "\\frac{a}{2} t^2 + v_0 t", "\\frac{a}{2} t^2 + v_0 t + C",
             "\\frac{a t^2}{2} + v_0 t", "\\frac{a t^2}{2} + v_0 t + C"
             ) 
squash_str <- "\\{|\\}| |\t|\n"

# To return the state of the app
if (!exists("apps_state")) apps_state <- reactiveValues() 

output[[NS(id, "rendered")]] <- renderUI({
  withMathJax(paste0("$$", input[[NS(id, "latex")]], "$$"))
})
output[[NS(id, "feedback")]] <- renderUI({
  compare <- gsub(squash_str, "", answers)
  the_answer <- input[[NS(id, "latex")]]
  if (is.null(the_answer)) the_answer <- "missing"
  correct <- gsub(squash_str, "", 
           input[[NS(id, "latex")]]) %in% compare
  if (exists("apps_state")) {
    registration_name <- NS(id, "result")
    apps_state[[registration_name]] <- 
      tibble::tibble(id = registration_name, 
                     question = "latex input",
                     answer = the_answer,
                     time = as.character(Sys.time()),
                     correct = correct,
                     attempts = 1,
                     history = "")
    
  }
  ifelse(correct, "✓", "☞")
})
```

