---
title: "Jumping between dimensions"
author: "Daniel Kaplan"
---

```{r goat-pitch-socks-setup, include = FALSE}
library(etude)

knitr::opts_chunk$set(echo = FALSE)
```

Choose the correct term for ____ in each of the following:


```{r goat1, echo=FALSE}
etude2::etudeQ(
  "Velocity is the _____ of acceleration (w.r.t. time)?",
    "2nd deriv" = "",
    "deriv" = "",
    "+anti-deriv+" = "",
    "2nd anti-deriv" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```

```{r goat2, echo=FALSE}
etude2::etudeQ(
  "Position is the _____ of velocity (w.r.t. time)?",
    "2nd deriv" = "",
    "deriv" = "",
    "+anti-deriv+" = "",
    "2nd anti-deriv" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```



```{r goat3, echo=FALSE}
etude2::etudeQ(
  "Acceleration is the _____ of position (w.r.t. time)?",
    "+2nd deriv+" = "",
    "deriv" = "",
    "anti-deriv" = "",
    "2nd anti-deriv" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```



```{r goat4, echo=FALSE}
etude2::etudeQ(
  "Energy is the ______ of force (w.r.t. time): ",
    "2nd deriv" = "",
    "deriv" = "",
    "anti-deriv" = "",
    "2nd anti-deriv" = "",
    "+none of the above+" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```


```{r goat5, echo=FALSE}
etude2::etudeQ(
  "Energy is the _____ of force (w.r.t. distance)?",
    "2nd deriv" = "",
    "deriv" = "",
    "+anti-deriv+" = "",
    "2nd anti-deriv" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```


```{r goat6, echo=FALSE}
etude2::etudeQ(
  "Cash is the _____ of cash flow (w.r.t. time)?",
    "2nd deriv" = "",
    "deriv" = "",
    "+anti-deriv+" = "",
    "2nd anti-deriv" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```


```{r goat7, echo=FALSE}
etude2::etudeQ(
  "Acceleration is the _____ of velocity (w.r.t. time)?",
    "2nd deriv" = "",
    "+deriv+" = "",
    "anti-deriv" = "",
    "2nd anti-deriv" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```

```{r goat8, echo=FALSE}
etude2::etudeQ(
  " Position is the _____ of velocity (w.r.t. time)?",
    "2nd deriv" = "",
    "deriv" = "",
    "+anti-deriv+" = "",
    "2nd anti-deriv" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```



```{r goat9, echo=FALSE}
etude2::etudeQ(
  "Distance is the _____ of acceleration (w.r.t. time)?",
    "2nd deriv" = "",
    "deriv" = "",
    "anti-deriv" = "",
    "+2nd anti-deriv+" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```



```{r goat10, echo=FALSE}
etude2::etudeQ(
  "Force is the ______ of momentum (w.r.t. time): ",
    "2nd deriv" = "",
    "deriv" = "",
    "+anti-deriv+" = "",
    "2nd anti-deriv" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```


```{r goat11, echo=FALSE}
etude2::etudeQ(
  "Force is the _____ of energy (w.r.t. distance)?",
    "2nd deriv" = "",
    "+deriv+" = "",
    "anti-deriv" = "",
    "2nd anti-deriv" = "",
    "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```


```{r goat12, echo=FALSE}
etude2::etudeQ(
  "Power is the _____ of energy (w.r.t. time)?",
  "2nd deriv" = "",
  "+deriv+" = "",
  "anti-deriv" = "",
  "2nd anti-deriv" = "",
  "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```

```{r goat13, echo=FALSE}
etude2::etudeQ(
  "Circumference of a circle is the _____ of area (w.r.t. radius)?",
  "2nd deriv" = "",
  "+deriv+" = "",
  "anti-deriv" = "",
  "2nd anti-deriv" = "",
  "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```

```{r goat14, echo=FALSE}
etude2::etudeQ(
  "Total cost is the _____ of marginal cost (w.r.t. quantity)?",
  "2nd deriv" = "",
  "deriv" = "",
  "+anti-deriv+" = "",
  "2nd anti-deriv" = "",
  "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```

```{r goat15, echo=FALSE}
etude2::etudeQ(
  "Births per year is part of the _____ of population size (w.r.t. time)?",
  "2nd deriv" = "",
  "+deriv+" = "",
  "anti-deriv" = "",
  "2nd anti-deriv" = "",
  "none of the above" = "",
  random_answer_order = FALSE,
  inline = FALSE
)
```

```{r goat16, echo=FALSE}
etude2::etudeQ(
  "Aside from births, what are other parts of the derivative of population size with respect to time?",
  "bankrupcies & deaths",
  "+net emigration & deaths+",
  "graduations & net emigration",
  "marriages & divorces"
)
```


